// ===== 生词本导入 第1批 (2026-08-17) 共630词 =====
// 来源: IMA 生词本_20260810_2125.pdf → 清洗去重(与 VDATA/VDATA_DELE 对照) → 语义例句生成
// 等级: 按 CEFR 自动分级 (A1/A2/B1/B2); 例句由 AI 逐词生成(语义贴合+语法校验)
const VDATA_BATCH1 = [
{"t": "trabajo", "es": "trabajar", "pos": "v.", "zh": "劳动；工作；努力；(机器等)运转；(工厂生产；耕作；加工；学习；精工制作；经营(某种商品)；办理；(工厂)生产", "ex": "Mi padre trabaja en una oficina desde hace diez años.", "lvl": "A1"},
{"t": "general", "es": "dormir", "pos": "v.", "zh": "睡觉；过夜；休眠；使人睡；麻醉；睡着；(肢体)麻木", "ex": "Normalmente duermo ocho horas todas las noches.", "lvl": "A1"},
{"t": "general", "es": "abandonar", "pos": "v.", "zh": "抛弃；放开；弃置不用；不理不顾；自暴自弃；不修边幅", "ex": "El dueño abandonó al perro en la calle.", "lvl": "B1"},
{"t": "general", "es": "acompañar", "pos": "v.", "zh": "伴同；随行；附加；具有；分享；分担；伴奏；会商", "ex": "Te acompaño al aeropuerto si quieres.", "lvl": "A2"},
{"t": "general", "es": "limitar", "pos": "v.", "zh": "划定界线；划定界限；限制；限定；约束；接壤；与...相毗邻；局限于；只限于", "ex": "España limita con Francia por el norte.", "lvl": "B1"},
{"t": "general", "es": "abrazar", "pos": "v.", "zh": "拥抱；抱住；包含；包围；信仰；搂住", "ex": "Al verme, mi abuela me abrazó con mucha alegría.", "lvl": "A2"},
{"t": "general", "es": "dar", "pos": "v.", "zh": "给予；交给；授予；任命；提出；提供；发生；使突然感到；(钟)打点；打；碰；转动；生长；(对某人)显得容易；致力于；沉湎于；屈从", "ex": "El profesor nos dio muchos consejos útiles.", "lvl": "A1"},
{"t": "emo", "es": "sentir", "pos": "v.", "zh": "感觉；感受；预感；遗憾；痛心；觉得；感到不适(或痛)；不满；裂开；感情；看法；见解", "ex": "Siento mucho no haber podido venir a tu fiesta.", "lvl": "A2"},
{"t": "general", "es": "organizar", "pos": "v.", "zh": "组织；组建；建立；安排生活(事务)；组成；形成", "ex": "Vamos a organizar una fiesta sorpresa para Ana.", "lvl": "A2"},
{"t": "diario", "es": "llegar", "pos": "v.", "zh": "到；(时间)到来；持续到；达到；实现；成为；靠近；靠拢", "ex": "El tren llegó a la estación con cinco minutos de retraso.", "lvl": "A1"},
{"t": "diario", "es": "salir", "pos": "v.", "zh": "出去；离开；伸出；长出；出版；(日、月等)升起；流出；漏出；逸掉；超出", "ex": "¿Quieres salir a cenar esta noche conmigo?", "lvl": "A1"},
{"t": "general", "es": "venir", "pos": "v.", "zh": "来到；来自；发生；接续；合适；生长；(从某处)来到；发酵；倒塌；破产", "ex": "Mis amigos van a venir a casa el sábado.", "lvl": "A1"},
{"t": "general", "es": "surgir", "pos": "v.", "zh": "冒出；撷错；出现；耸立；抛错", "ex": "Durante la reunión surgieron varias preguntas importantes.", "lvl": "B1"},
{"t": "general", "es": "significar", "pos": "v.", "zh": "意味着；标志着；表明；说明；有重要性；有作用；突出；引人注目；显示(态度等)", "ex": "Esa señal significa que está prohibido aparcar aquí.", "lvl": "B1"},
{"t": "soc", "es": "desarrollar", "pos": "v.", "zh": "展开；使成长；发展；阐述；实施；展开(方程式)；成长；发生", "ex": "La empresa quiere desarrollar nuevos productos para el mercado.", "lvl": "B1"},
{"t": "general", "es": "señalar", "pos": "v.", "zh": "标志；作记号；确定；暗指；讨论；出众；闻名", "ex": "El profesor señaló los errores del ejercicio en clase.", "lvl": "B1"},
{"t": "general", "es": "explicar", "pos": "v.", "zh": "解释；讲解；明白；表达", "ex": "¿Me puedes explicar cómo funciona este teléfono?", "lvl": "A2"},
{"t": "general", "es": "reír", "pos": "v.", "zh": "笑；嘲笑；欢快；(通过笑声等对某件事情)表示赞赏；破裂", "ex": "La película era tan divertida que no parábamos de reír.", "lvl": "A2"},
{"t": "general", "es": "volver", "pos": "v.", "zh": "翻；转动；转向；卷起 (衣袖等)；翻新(衣服)；还回；返回；继续；重又；又；转身；转头；变成；改变观点", "ex": "Volveré a casa temprano esta noche.", "lvl": "A2"},
{"t": "general", "es": "morir", "pos": "v.", "zh": "死亡；去世；熄灭；完结；消失；强烈地感到；渴望(得到)；(肢体)麻木", "ex": "El abuelo murió hace dos años en su pueblo.", "lvl": "A2"},
{"t": "diario", "es": "correr", "pos": "v.", "zh": "跑；急忙；(时间)流逝；流动；流通；跑遍；抢劫；挪动；过快熔化；过分；度过", "ex": "Todos los días corro treinta minutos en el parque.", "lvl": "A1"},
{"t": "general", "es": "afirmar", "pos": "v.", "zh": "使固定；肯定；断言；说明；prml. 牢固；稳固；确定；确信", "ex": "El testigo afirmó que vio al ladrón salir del banco.", "lvl": "B1"},
{"t": "general", "es": "esforzar", "pos": "v.", "zh": "使有力；激励；使费力；振作；振奋；努力；尽力", "ex": "Debes esforzarte más si quieres aprobar el examen.", "lvl": "B1"},
{"t": "general", "es": "nacer", "pos": "v.", "zh": "出生；出壳；长出；出身；升起；产生；发源；发芽；开线", "ex": "Mi hermana nació en el mes de abril.", "lvl": "A2"},
{"t": "general", "es": "decidir", "pos": "v.", "zh": "决定；裁决；使下决心；作出决定；决心", "ex": "Hemos decidido viajar a Madrid el próximo verano.", "lvl": "A2"},
{"t": "comida", "es": "llenar", "pos": "v.", "zh": "使满；占满；使吃饱；填写(表格)；使充满(某种感情)；(月亮)变圆；吃饱；生气", "ex": "Tienes que llenar este formulario con tus datos personales.", "lvl": "A2"},
{"t": "general", "es": "pasear", "pos": "v.", "zh": "散步；闲逛；漫步行走；哄孩子；遮(马、狗)；闲散；无事可做", "ex": "Mis abuelos pasean por el parque todas las tardes.", "lvl": "A1"},
{"t": "general", "es": "acabar", "pos": "v.", "zh": "完成；结束；耗尽；进行最后加工；死亡；消灭；刚刚；终于", "ex": "La película acaba a las diez de la noche.", "lvl": "A2"},
{"t": "edu", "es": "aprobar", "pos": "v.", "zh": "赞成；通过；评为合格；通过(考试、考核)", "ex": "Estoy seguro de que vas a aprobar el examen de español.", "lvl": "B1"},
{"t": "naturaleza", "es": "costar", "pos": "v.", "zh": "花费；耗费；使以...为代价；使费力；使费难", "ex": "Ese coche cuesta demasiado dinero para mí.", "lvl": "A2"},
{"t": "general", "es": "proceder", "pos": "v.", "zh": "来自；源自；表现；做为；合乎情理；开始进行；行为", "ex": "El juez procedió a leer la sentencia.", "lvl": "B2"},
{"t": "general", "es": "explotar", "pos": "v.", "zh": "爆炸；开发；利用；剥削", "ex": "Algunas empresas explotan a sus empleados con sueldos bajos.", "lvl": "B2"},
{"t": "general", "es": "amenazar", "pos": "v.", "zh": "威胁；恫吓；有发生...的迹象", "ex": "El ladrón amenazó al cajero con un cuchillo.", "lvl": "B1"},
{"t": "general", "es": "detener", "pos": "v.", "zh": "阻止；使停止；扣留；逮捕；拘留；停留；耽搁；延误", "ex": "La policía detuvo al ladrón cerca del supermercado.", "lvl": "B1"},
{"t": "general", "es": "insistir", "pos": "v.", "zh": "坚持；执意；坚决认为；坚决主张", "ex": "Insisto en que debemos salir antes de las seis.", "lvl": "B1"},
{"t": "soc", "es": "andar", "pos": "v.", "zh": "走；运行；(事情)发展；处于(某种状态)；走过；走遍；着手开始；走路的姿势；表现；举止", "ex": "El niño ya anda sin ayuda de sus padres.", "lvl": "A2"},
{"t": "naturaleza", "es": "vaciar", "pos": "v.", "zh": "腾出；倒空；挖空；铸造；浇制；把...磨锋利；(河流)流入；汇入；和盘托出", "ex": "Hay que vaciar la botella antes de reciclarla.", "lvl": "B1"},
{"t": "general", "es": "encargar", "pos": "v.", "zh": "委托；嘱咐；定购；负责", "ex": "Me encargo yo de comprar las entradas.", "lvl": "B1"},
{"t": "general", "es": "adquirir", "pos": "v.", "zh": "取得；获得；赢得；换得；购得", "ex": "He adquirido mucha experiencia trabajando en el extranjero.", "lvl": "B2"},
{"t": "trabajo", "es": "manejar", "pos": "v.", "zh": "掌握；使用；管理；控制；驾驭；驾驶；变灵活；处理", "ex": "Ella maneja el coche con mucha prudencia.", "lvl": "B1"},
{"t": "general", "es": "distinguir", "pos": "v.", "zh": "辨别；有别于；分别处理；器重；突出；杰出", "ex": "A esta distancia no puedo distinguir bien las letras.", "lvl": "B1"},
{"t": "general", "es": "garantizar", "pos": "v.", "zh": "保证；肯定；保障；保用", "ex": "La tienda garantiza la calidad de todos sus productos.", "lvl": "B2"},
{"t": "general", "es": "compartir", "pos": "v.", "zh": "分配；分享；共用；共有；分担", "ex": "Me gusta compartir mis experiencias con los compañeros.", "lvl": "A2"},
{"t": "general", "es": "ejercer", "pos": "v.", "zh": "从事；施；行；实行；行使", "ex": "Mi tía ejerce la medicina en un hospital de Madrid.", "lvl": "B2"},
{"t": "general", "es": "introducir", "pos": "v.", "zh": "插入；放入；引进；传入；刻画", "ex": "Introduce la tarjeta en la máquina para pagar.", "lvl": "B1"},
{"t": "casa", "es": "domiciliar", "pos": "v.", "zh": "给住所；(在信封上) 写地址；定居；安家", "ex": "Mi tía se domicilió en Valencia hace diez años.", "lvl": "B2"},
{"t": "general", "es": "abundar", "pos": "v.", "zh": "丰富；盛产；坚持", "ex": "Los peces abundan en este río cristalino.", "lvl": "B2"},
{"t": "edu", "es": "enfocar", "pos": "v.", "zh": "(用灯等) 照；对准；使聚焦；分析；研究", "ex": "Enfoca la cámara hacia el monumento y dispara.", "lvl": "B1"},
{"t": "general", "es": "versar", "pos": "v.", "zh": "环绕；论及；论述；精通", "ex": "La conferencia versa sobre el cambio climático.", "lvl": "B2"},
{"t": "general", "es": "fijar", "pos": "v.", "zh": "固定；固着；确定；集中；prml. 决定；注意；发觉", "ex": "Tenemos que fijar la fecha de la reunión.", "lvl": "B1"},
{"t": "general", "es": "simplificar", "pos": "v.", "zh": "简化；精简", "ex": "Podemos simplificar este proceso para ahorrar tiempo.", "lvl": "B2"},
{"t": "general", "es": "atravesar", "pos": "v.", "zh": "模放；楔穿；穿过；穿透；使痛苦；模在中间；插话；反感；意外发生", "ex": "El puente atraviesa el río de lado a lado.", "lvl": "B1"},
{"t": "general", "es": "contribuir", "pos": "v.", "zh": "缴纳(捐税)；捐赠；作出贡献；助长", "ex": "Todos los voluntarios contribuyeron al éxito del evento.", "lvl": "B1"},
{"t": "general", "es": "acostumbrar", "pos": "v.", "zh": "使习惯；使适应；有...习惯；养成习惯", "ex": "Tienes que acostumbrarte al clima frío de esta ciudad.", "lvl": "B1"},
{"t": "general", "es": "reforzar", "pos": "v.", "zh": "加强；加固；增加；鼓舞；加厚", "ex": "El equipo reforzó su defensa en el segundo tiempo.", "lvl": "B2"},
{"t": "general", "es": "derivar", "pos": "v.", "zh": "引向；引出；使派生出；求导数；转向；来自；偏航；改变；改换；出来；伸出；产生", "ex": "La palabra 'panadería' deriva de 'pan'.", "lvl": "B2"},
{"t": "general", "es": "abordar", "pos": "v.", "zh": "接触；相撞；停靠；上前攀谈；着手处理；登机", "ex": "El informe aborda varios problemas sociales importantes.", "lvl": "B2"},
{"t": "general", "es": "confiar", "pos": "v.", "zh": "相信；信任；委托；托付", "ex": "Confío plenamente en mi mejor amiga.", "lvl": "B1"},
{"t": "general", "es": "estimular", "pos": "v.", "zh": "刺激；鼓励", "ex": "Los elogios estimulan a los niños a estudiar mejor.", "lvl": "B2"},
{"t": "general", "es": "abrigar", "pos": "v.", "zh": "使不受风寒侵袭；庇护；怀抱", "ex": "La madre abrigó al bebé con una manta gruesa.", "lvl": "B1"},
{"t": "general", "es": "certificar", "pos": "v.", "zh": "证明；(给邮件) 挂号", "ex": "El médico certificó que el paciente estaba sano.", "lvl": "B2"},
{"t": "general", "es": "proporcionar", "pos": "v.", "zh": "使成比例；使匀称；提供；供给", "ex": "El hotel proporciona toallas limpias a todos los huéspedes.", "lvl": "B2"},
{"t": "general", "es": "interrumpir", "pos": "v.", "zh": "中断；使暂停；打断(谈话、活动)；插嘴", "ex": "Perdona que te interrumpa, pero tengo una duda.", "lvl": "B1"},
{"t": "emo", "es": "suspender", "pos": "v.", "zh": "悬；暂停；使不及格；使惊呆", "ex": "Suspendí el examen de matemáticas el mes pasado.", "lvl": "B1"},
{"t": "edu", "es": "profundizar", "pos": "v.", "zh": "加深；使更深；深入研究", "ex": "Quiero profundizar en el estudio de la gramática española.", "lvl": "B2"},
{"t": "general", "es": "inclinar", "pos": "v.", "zh": "使倾斜；弯；屈；影响；促使；使倾向；相似；近似；倾向；偏向；想要；打算", "ex": "Me inclino a creer que tiene razón.", "lvl": "B1"},
{"t": "general", "es": "extraer", "pos": "v.", "zh": "取出；提取；摘录；吸取；求(根)", "ex": "El dentista me extrajo una muela el lunes.", "lvl": "B2"},
{"t": "naturaleza", "es": "hervir", "pos": "v.", "zh": "沸腾；(发酵时)冒气泡；(大海)波浪翻滚；(情绪)激昂；充满；焦沸", "ex": "El agua hierve a cien grados.", "lvl": "A2"},
{"t": "general", "es": "estallar", "pos": "v.", "zh": "爆炸；爆发；发出清脆的响声；忍不住", "ex": "La tormenta estalló de repente en plena noche.", "lvl": "B1"},
{"t": "salud", "es": "golpear", "pos": "v.", "zh": "(连续)打；击；敲；拍；使受打击；拍打(身体某部分)", "ex": "Alguien golpeó la puerta con mucha fuerza.", "lvl": "A2"},
{"t": "comida", "es": "cocer", "pos": "v.", "zh": "煮；烤；烧制；煮沸；开锅；发酵；热得难受；忍受 (苦痛等的) 折磨；烦躁；焦躁", "ex": "Para la paella, primero hay que cocer el arroz.", "lvl": "A2"},
{"t": "general", "es": "aconsejar", "pos": "v.", "zh": "劝告；启发；提示；向... 请教；同... 商量；征求...意见", "ex": "El médico me aconsejó descansar unos días.", "lvl": "B1"},
{"t": "general", "es": "deducir", "pos": "v.", "zh": "推断；扣除；申辩", "ex": "De sus palabras deduzco que está muy cansado.", "lvl": "B2"},
{"t": "general", "es": "retener", "pos": "v.", "zh": "保留；挽留；记住；保留(职务)；扣留", "ex": "Es difícil retener todas las palabras nuevas.", "lvl": "B2"},
{"t": "tec", "es": "accionar", "pos": "v.", "zh": "启动(机器等)；做手势；起诉", "ex": "Acciona el botón rojo para encender la máquina.", "lvl": "B2"},
{"t": "general", "es": "discernir", "pos": "v.", "zh": "识别；分辨；辨别；指定 (监护人等)；授予", "ex": "Es difícil discernir la verdad de la mentira en este caso.", "lvl": "B2"},
{"t": "general", "es": "atarapar", "pos": "v.", "zh": "捉住；捞到；欺骗", "ex": "El gato atrapó un ratón en el jardín.", "lvl": "B2"},
{"t": "general", "es": "especificar", "pos": "v.", "zh": "详细说明", "ex": "Por favor, especifica qué tipo de habitación quieres.", "lvl": "B2"},
{"t": "comida", "es": "ingerir", "pos": "v.", "zh": "(动物) 吃下；吞下", "ex": "No debes ingerir alimentos dos horas antes de la operación.", "lvl": "B2"},
{"t": "general", "es": "debilitar", "pos": "v.", "zh": "使衰弱；减弱", "ex": "La enfermedad debilitó mucho al paciente.", "lvl": "B2"},
{"t": "general", "es": "erguir", "pos": "v.", "zh": "竖起；使直立；直立；耸立；挺直；起立；骄傲", "ex": "El soldado se irguió ante el capitán.", "lvl": "B2"},
{"t": "general", "es": "persuadir", "pos": "v.", "zh": "使信服；说服；劝服；明白；懂得；相信", "ex": "Lo persuadí para que aceptara el trabajo.", "lvl": "B2"},
{"t": "general", "es": "priorizar", "pos": "v.", "zh": "优先考虑", "ex": "Debemos priorizar la seguridad de los niños.", "lvl": "B2"},
{"t": "general", "es": "empacar", "pos": "v.", "zh": "包装；打包；装箱；顽固坚持；固执", "ex": "Ya he empacado todas mis cosas para el viaje.", "lvl": "B1"},
{"t": "general", "es": "deslindar", "pos": "v.", "zh": "划定；确定范围；弄清楚", "ex": "Hay que deslindar bien las responsabilidades de cada uno.", "lvl": "B2"},
{"t": "general", "es": "acceden", "pos": "v.", "zh": "同意；进入", "ex": "Los estudiantes acceden a la biblioteca con su carnet.", "lvl": "B1"},
{"t": "tec", "es": "accione", "pos": "v.", "zh": "启动(机器等)；做手势；起诉", "ex": "Espero que accione la máquina con cuidado.", "lvl": "B2"},
{"t": "tec", "es": "acciones", "pos": "v.", "zh": "启动(机器等)；做手势；起诉", "ex": "Si acciones este botón, la máquina se detiene.", "lvl": "B2"},
{"t": "emo", "es": "aficionarse", "pos": "v.", "zh": "喜欢；喜爱", "ex": "Me he aficionado al fútbol gracias a mi hermano.", "lvl": "B1"},
{"t": "general", "es": "concibe", "pos": "v.", "zh": "受孕；构思", "ex": "El escritor concibe nuevas ideas para su novela.", "lvl": "B2"},
{"t": "general", "es": "constituye", "pos": "v.", "zh": "组成；是；建立；设立；指派；到达；担任", "ex": "El agua constituye la mayor parte de nuestro cuerpo.", "lvl": "B2"},
{"t": "general", "es": "convertir", "pos": "v.", "zh": "使变成；使成为；使信教；使改变信仰；使转向；成为；皈依", "ex": "La ciudad se fue convirtiendo en un gran centro turístico.", "lvl": "B1"},
{"t": "general", "es": "creerse", "pos": "v.", "zh": "相信；以为；信教", "ex": "No te creas todo lo que lees en Internet.", "lvl": "A2"},
{"t": "diario", "es": "cumplan", "pos": "v.", "zh": "执行；完成；提供；满...岁；服刑；尽到责任；方便；到期；适合；满 (多少时间、年、月等)；实现", "ex": "Espero que todos cumplan sus promesas.", "lvl": "A2"},
{"t": "general", "es": "definía", "pos": "v.", "zh": "下定义；表明；确定；最后完成 (作品)", "ex": "El profesor definía los conceptos con ejemplos claros.", "lvl": "B1"},
{"t": "emo", "es": "deseaba", "pos": "v.", "zh": "想要；希望；要求；祝愿", "ex": "Deseaba visitar España desde que era pequeño.", "lvl": "A2"},
{"t": "general", "es": "destacan", "pos": "v.", "zh": "分谱；使醒目；强调；突出；出众", "ex": "Estos artistas destacan por su talento musical.", "lvl": "B1"},
{"t": "general", "es": "detenerse", "pos": "v.", "zh": "停住；耽搁", "ex": "El autobús se detiene en cada esquina.", "lvl": "B1"},
{"t": "general", "es": "dispone", "pos": "v.", "zh": "布置；安排；准备；吩 附；拥有；自由支配；得到 (某人的) 帮助；想；打算；做好准备", "ex": "La empresa dispone de una sala grande para reuniones.", "lvl": "B1"},
{"t": "general", "es": "ducharse", "pos": "v.", "zh": "洗淋浴", "ex": "Me ducho todas las mañanas antes de desayunar.", "lvl": "A1"},
{"t": "naturaleza", "es": "empleaban", "pos": "v.", "zh": "雇用；用；花费", "ex": "Antiguamente empleaban caballos para transportar mercancías.", "lvl": "B1"},
{"t": "general", "es": "garanticen", "pos": "v.", "zh": "保证；肯定；保障；保用", "ex": "Espero que garanticen la seguridad de los visitantes.", "lvl": "B2"},
{"t": "general", "es": "generan", "pos": "v.", "zh": "繁殖；产生", "ex": "Las fábricas generan muchos residuos contaminantes.", "lvl": "B1"},
{"t": "general", "es": "influir", "pos": "v.", "zh": "影响", "ex": "El clima influye mucho en mi estado de ánimo.", "lvl": "B1"},
{"t": "general", "es": "intervienen", "pos": "v.", "zh": "参与；干预；发言；调解；开刀；动手术；查(账)；审计；陈述式现在时(Indicativo Presente)", "ex": "Varios expertos intervienen en la reunión de hoy.", "lvl": "B2"},
{"t": "general", "es": "introdujo", "pos": "v.", "zh": "插入；放入；引进；传入；刻画｜陈述式简单过去时(Indicativo Pretérito Perfecto Simple)", "ex": "El ladrón introdujo la llave en la cerradura.", "lvl": "B1"},
{"t": "general", "es": "llevarse", "pos": "v.", "zh": "带走；相处", "ex": "Mis hermanos se llevan muy bien entre ellos.", "lvl": "A2"},
{"t": "general", "es": "mantiene", "pos": "v.", "zh": "养活；赡养；支撑；使维持生命；支持；维持；履行；主持(比赛等)；生活；生存；维持生命｜陈述式现在时(Indicativo Presente)", "ex": "El atleta mantiene un ritmo constante durante la carrera.", "lvl": "B1"},
{"t": "general", "es": "modificarlo", "pos": "v.", "zh": "修改；改变；修饰", "ex": "El plan no me gusta, así que voy a modificarlo.", "lvl": "B1"},
{"t": "general", "es": "ponerse", "pos": "v.", "zh": "穿；戴；打扮", "ex": "Me pongo el jersey gris cuando hace frío.", "lvl": "A2"},
{"t": "general", "es": "presiones", "pos": "v.", "zh": "压；压迫；施加压力；强迫；威逼", "ex": "No me presiones, necesito tiempo para pensar.", "lvl": "B1"},
{"t": "general", "es": "promocionar", "pos": "v.", "zh": "推销；提升", "ex": "La marca promociona su nuevo teléfono en televisión.", "lvl": "B2"},
{"t": "general", "es": "protegen", "pos": "v.", "zh": "保护；支持；帮助；鼓励", "ex": "Estas leyes protegen a los animales en peligro.", "lvl": "A2"},
{"t": "general", "es": "refleja", "pos": "v.", "zh": "反射(光、热、声等)；照出；反映", "ex": "Su cara refleja toda la alegría que siente.", "lvl": "B1"},
{"t": "general", "es": "reservaba", "pos": "v.", "zh": "保存；留存；储存；保留；预订", "ex": "Cuando vivía en Madrid, siempre reservaba mesa en ese restaurante.", "lvl": "A2"},
{"t": "general", "es": "restrinjan", "pos": "v.", "zh": "限制；约束；压缩；紧缩", "ex": "Espero que no restrinjan el acceso a la información.", "lvl": "B2"},
{"t": "general", "es": "resurge", "pos": "v.", "zh": "再现；振作；康复", "ex": "La economía resurge después de la crisis.", "lvl": "B2"},
{"t": "general", "es": "rodea", "pos": "v.", "zh": "绕道而行；绕圈子；(说话)拐弯抹角；环绕；包围；围住；处于...之中；调转方向；团团打转", "ex": "Una valla alta rodea el jardín de la casa.", "lvl": "B1"},
{"t": "diario", "es": "salir a", "pos": "v.", "zh": "出去；离开；伸出；长出；出版；(日、月等)升起；流出；漏出；选择；超出", "ex": "Los niños salen a jugar al patio después de comer.", "lvl": "A1"},
{"t": "trabajo", "es": "servirse", "pos": "v.", "zh": "工作；供职；能用；可用；充当tr. 服务；效力", "ex": "Los científicos se sirven de datos exactos para sus estudios.", "lvl": "B1"},
{"t": "general", "es": "sigue", "pos": "v.", "zh": "跟随；跟踪；注视；遵循；奉行；由...看来；接着；接连；接续", "ex": "Todavía sigue lloviendo desde esta mañana.", "lvl": "A2"},
{"t": "soc", "es": "socializando", "pos": "v.", "zh": "使社会化；使公有化；社交", "ex": "Llevo toda la noche socializando con los invitados.", "lvl": "B2"},
{"t": "general", "es": "suele", "pos": "v.", "zh": "惯于；经常；时常", "ex": "Mi abuelo suele levantarse muy temprano.", "lvl": "A2"},
{"t": "general", "es": "suponen", "pos": "v.", "zh": "假定；猜想；想象；意味着；表明", "ex": "Esas cifras suponen un gran avance para el país.", "lvl": "B1"},
{"t": "general", "es": "universalizan", "pos": "v.", "zh": "使普遍化；普及", "ex": "Las nuevas tecnologías universalizan el acceso a la educación.", "lvl": "B2"},
{"t": "general", "es": "volverse", "pos": "v.", "zh": "变成；成为", "ex": "Con los años, mi padre se ha vuelto más tranquilo.", "lvl": "A2"},
{"t": "trabajo", "es": "semana", "pos": "f.", "zh": "星期；周薪；周工资；七日(周、年、世纪)", "ex": "La próxima semana tengo vacaciones y viajo a la costa.", "lvl": "A1"},
{"t": "salud", "es": "hospital", "pos": "m.", "zh": "医院", "ex": "Mi abuela está en el hospital desde el lunes.", "lvl": "A1"},
{"t": "comida", "es": "carne", "pos": "f.", "zh": "肉；(食用)肉；肉食；果肉；肉体；肉欲", "ex": "No como carne porque soy vegetariana.", "lvl": "A1"},
{"t": "naturaleza", "es": "flor", "pos": "f.", "zh": "花；花卉；开花植物；观赏植物；精华；精粹", "ex": "Compré una flor para regalar a mi madre.", "lvl": "A1"},
{"t": "general", "es": "museo", "pos": "m.", "zh": "博物馆；文物馆；展览馆", "ex": "Fuimos al museo a ver cuadros antiguos.", "lvl": "A1"},
{"t": "general", "es": "parque", "pos": "m.", "zh": "公园；(限制幼儿活动范围用的)活动拦杆；停车场", "ex": "Los niños juegan en el parque cada tarde.", "lvl": "A1"},
{"t": "naturaleza", "es": "jardín", "pos": "m.", "zh": "花园；公园", "ex": "Mi casa tiene un jardín lleno de flores.", "lvl": "A1"},
{"t": "naturaleza", "es": "playa", "pos": "f.", "zh": "海滩；河滩", "ex": "En verano vamos a la playa a nadar.", "lvl": "A1"},
{"t": "diario", "es": "invierno", "pos": "m.", "zh": "冬季；冬天", "ex": "En invierno hace mucho frío en mi ciudad.", "lvl": "A1"},
{"t": "naturaleza", "es": "montaña", "pos": "f.", "zh": "山；山岳；山区；大堆；困难；难事", "ex": "Subimos la montaña temprano por la mañana.", "lvl": "A1"},
{"t": "edu", "es": "biblioteca", "pos": "f.", "zh": "图书馆；藏书；书架", "ex": "Estudio en la biblioteca porque hay silencio.", "lvl": "A1"},
{"t": "comida", "es": "arroz", "pos": "m.", "zh": "水稻；稻米", "ex": "La paella se hace con arroz y mariscos.", "lvl": "A1"},
{"t": "naturaleza", "es": "pollo", "pos": "m.", "zh": "雏鸟；鸡雏；子鸡；幼畜；幼兽；幼虫", "ex": "Para cenar preparamos pollo con patatas.", "lvl": "A1"},
{"t": "casa", "es": "piso", "pos": "m.", "zh": "地面；地板；(楼房的)层；成套房间", "ex": "Vivimos en un piso pequeño en el centro.", "lvl": "A1"},
{"t": "comida", "es": "verdura", "pos": "f.", "zh": "绿色；青翠；蔬菜；枝叶；好色", "ex": "Debes comer verdura para estar sano.", "lvl": "A1"},
{"t": "naturaleza", "es": "rostro", "pos": "m.", "zh": "脸；面孔；鸟喙；嘴；船首", "ex": "El miedo se reflejaba en su rostro.", "lvl": "B1"},
{"t": "general", "es": "chaqueta", "pos": "f.", "zh": "外衣；外套", "ex": "Me pongo la chaqueta porque hace frío.", "lvl": "A2"},
{"t": "general", "es": "movilidad", "pos": "f.", "zh": "流动性；活动性；易变性", "ex": "La movilidad entre ciudades mejora con el tren.", "lvl": "B1"},
{"t": "general", "es": "marco", "pos": "m.", "zh": "框；框子；框架；规格；尺码", "ex": "Compré un marco dorado para la foto.", "lvl": "B1"},
{"t": "general", "es": "pelo", "pos": "m.", "zh": "毛；细毛；绒毛；纤毛；头发", "ex": "María tiene el pelo largo y negro.", "lvl": "A1"},
{"t": "general", "es": "intensidad", "pos": "f.", "zh": "强度；强烈", "ex": "La intensidad del terremoto fue muy alta.", "lvl": "B1"},
{"t": "diario", "es": "mes", "pos": "m.", "zh": "月；月份；月经；月薪", "ex": "El próximo mes empiezo un curso nuevo.", "lvl": "A1"},
{"t": "general", "es": "cine", "pos": "m.", "zh": "电影；电影院", "ex": "Vamos al cine a ver una película.", "lvl": "A1"},
{"t": "general", "es": "jefe", "pos": "m.", "zh": "首领；首长；头目", "ex": "Mi jefe me pidió terminar el informe hoy.", "lvl": "A2"},
{"t": "naturaleza", "es": "mano", "pos": "f.", "zh": "手；(四蹄动物的) 前爪；前蹄；(猛禽的) 爪", "ex": "Me lavo las manos antes de comer.", "lvl": "A1"},
{"t": "general", "es": "opinión", "pos": "f.", "zh": "意见；看法；名声；公众舆论；政见", "ex": "En mi opinión, esta es la mejor opción.", "lvl": "B1"},
{"t": "general", "es": "unidad", "pos": "f.", "zh": "单一性；个体；单元；单位；统一；团结", "ex": "La unidad del equipo es muy importante.", "lvl": "B1"},
{"t": "trabajo", "es": "actividad", "pos": "f.", "zh": "活动性；勤快；敏捷；活动；职业", "ex": "El museo ofrece una actividad para niños.", "lvl": "A2"},
{"t": "general", "es": "cambio", "pos": "m.", "zh": "改变；变化；交换；零钱；兑换率", "ex": "El cambio climático preocupa a todos.", "lvl": "A2"},
{"t": "soc", "es": "paz", "pos": "f.", "zh": "和平；和好；和睦", "ex": "Todos queremos vivir en paz y armonía.", "lvl": "B1"},
{"t": "general", "es": "haber", "pos": "m.", "zh": "财产；资产；贷方；aux.一定；必须；发生；有；存在；拿到；到手", "ex": "El haber de la empresa es mayor que su deuda.", "lvl": "B1"},
{"t": "general", "es": "honestidad", "pos": "f.", "zh": "诚实；正直；正派；认真", "ex": "La honestidad es muy valorada en mi trabajo.", "lvl": "B1"},
{"t": "general", "es": "energía", "pos": "f.", "zh": "效力；力量；能力；精力；能；能量", "ex": "Los niños tienen mucha energía por la mañana.", "lvl": "B1"},
{"t": "general", "es": "fiesta", "pos": "f.", "zh": "节日；欢会；聚会；庆祝；活动；愉快的事；亲热", "ex": "El sábado hay fiesta en casa de Ana.", "lvl": "A1"},
{"t": "general", "es": "piel", "pos": "f.", "zh": "皮；皮肤；兽皮；毛皮；皮革", "ex": "El sol daña la piel si no usas protección.", "lvl": "A2"},
{"t": "general", "es": "pintura", "pos": "f.", "zh": "绘画；绘画作品；颜料；油漆", "ex": "Esta pintura se seca en una hora.", "lvl": "A2"},
{"t": "general", "es": "síndrome", "pos": "m.", "zh": "综合征；征群；综合症状", "ex": "El síndrome de fatiga afecta a muchos trabajadores.", "lvl": "B2"},
{"t": "soc", "es": "revolución", "pos": "f.", "zh": "革命；激变；剧变；旋转；回转；公转", "ex": "La revolución industrial cambió el mundo.", "lvl": "B1"},
{"t": "emo", "es": "calor", "pos": "m.", "zh": "热；热能；热量；热烈；热情；最激烈的时刻", "ex": "En agosto hace mucho calor por aquí.", "lvl": "A1"},
{"t": "soc", "es": "cuestión", "pos": "f.", "zh": "问题；事情；疑难；争吵", "ex": "Es una cuestión de tiempo que llegue.", "lvl": "B1"},
{"t": "general", "es": "clientela", "pos": "f.", "zh": "保护；监护；主顾；顾客", "ex": "El restaurante tiene mucha clientela los fines de semana.", "lvl": "B2"},
{"t": "general", "es": "edificio", "pos": "m.", "zh": "建筑物；大楼", "ex": "Ese edificio nuevo tiene veinte pisos.", "lvl": "A2"},
{"t": "general", "es": "micrófono", "pos": "m.", "zh": "麦克风；话筒；微音器；送话器；传声器", "ex": "El cantante habló por el micrófono.", "lvl": "A2"},
{"t": "naturaleza", "es": "viento", "pos": "m.", "zh": "风；空气；(猎物留下的) 具迹；(动物的) 嗅觉", "ex": "El viento derribó algunos árboles de la calle.", "lvl": "A1"},
{"t": "general", "es": "dedo", "pos": "m.", "zh": "手指；脚趾", "ex": "Me corté el dedo con un cuchillo.", "lvl": "A1"},
{"t": "general", "es": "pierna", "pos": "f.", "zh": "腿", "ex": "Le duele la pierna después de correr.", "lvl": "A1"},
{"t": "general", "es": "propósito", "pos": "m.", "zh": "企图；意图；目的；目标；题目；论题", "ex": "Su propósito es aprender español este año.", "lvl": "B1"},
{"t": "casa", "es": "pieza", "pos": "f.", "zh": "个；物品；零件；(布的) 匹；(纸的简；房间；棋子)", "ex": "Me falta una pieza del rompecabezas.", "lvl": "A2"},
{"t": "general", "es": "tráfico", "pos": "m.", "zh": "买卖；贩卖；倒卖；交通", "ex": "El tráfico en esta calle es terrible.", "lvl": "B1"},
{"t": "general", "es": "víctima", "pos": "f.", "zh": "牺牲；牺牲者；受害者；牺牲品", "ex": "La víctima fue llevada al hospital.", "lvl": "B1"},
{"t": "general", "es": "huevo", "pos": "m.", "zh": "卵；蛋；鸡蛋；卵形物", "ex": "Desayuno un huevo con pan cada mañana.", "lvl": "A1"},
{"t": "general", "es": "fórmula", "pos": "f.", "zh": "方式；处方；配方；公式；式；(公文等)格式", "ex": "La fórmula química del agua es H2O.", "lvl": "B1"},
{"t": "general", "es": "reacción", "pos": "f.", "zh": "反应；反作用(力)；反动；反动派；反馈", "ex": "La reacción de los fans fue increíble.", "lvl": "B1"},
{"t": "general", "es": "division", "pos": "f.", "zh": "分开；分裂；除；除法", "ex": "En clase aprendimos a hacer divisiones.", "lvl": "B1"},
{"t": "general", "es": "geografia", "pos": "f.", "zh": "地理；地貌；地区", "ex": "En clase de geografía estudiamos los ríos.", "lvl": "B1"},
{"t": "casa", "es": "espalda", "pos": "f.", "zh": "背；背部；背背；(衣服的)后身；椅背；仰泳；防护墙", "ex": "Me duele la espalda por trabajar tanto.", "lvl": "A2"},
{"t": "general", "es": "esfuerzo", "pos": "m.", "zh": "努力；勇气；节俭", "ex": "Con esfuerzo puedes lograr tus metas.", "lvl": "B1"},
{"t": "general", "es": "filosofía", "pos": "f.", "zh": "哲学；哲理；哲学体系；哲学系；达观；泰然", "ex": "Quiero estudiar filosofía en la universidad.", "lvl": "B2"},
{"t": "naturaleza", "es": "curso", "pos": "m.", "zh": "水流；流程；(星球运行的)轨道；过程；进展；学年；年级；班级；一个年级的学生；教程；课程", "ex": "Este curso estudiamos la historia de España.", "lvl": "A2"},
{"t": "trabajo", "es": "sesión", "pos": "f.", "zh": "会议；(演出等的)场", "ex": "La sesión de cine empieza a las ocho.", "lvl": "B1"},
{"t": "soc", "es": "terrorismo", "pos": "m.", "zh": "恐怖主义；恐怖制度", "ex": "El terrorismo es un problema mundial.", "lvl": "B2"},
{"t": "general", "es": "claridad", "pos": "f.", "zh": "光亮；透明；清楚；清醒；敏锐；坦率", "ex": "Habló con claridad y todos lo entendieron.", "lvl": "B1"},
{"t": "general", "es": "grado", "pos": "m.", "zh": "台阶；阶梯；等级；学位；刻度；标度；尺度；度数；意愿；阶段", "ex": "El termómetro marca treinta grados hoy.", "lvl": "B1"},
{"t": "general", "es": "camisa", "pos": "f.", "zh": "衬衫", "ex": "Me compré una camisa blanca para la entrevista.", "lvl": "A1"},
{"t": "general", "es": "barco", "pos": "m.", "zh": "船；舰", "ex": "El barco salió del puerto a las diez.", "lvl": "A1"},
{"t": "general", "es": "queso", "pos": "m.", "zh": "乳酪；奶酪；干酪", "ex": "El queso manchego es muy famoso.", "lvl": "A1"},
{"t": "general", "es": "zapatilla", "pos": "f.", "zh": "(室内穿的) 便鞋；舞鞋", "ex": "Me pongo las zapatillas para correr.", "lvl": "A2"},
{"t": "general", "es": "sindicato", "pos": "m.", "zh": "工会；辛迪加；企业联合会", "ex": "El sindicato negoció mejores salarios con la empresa.", "lvl": "B2"},
{"t": "general", "es": "núcleo", "pos": "m.", "zh": "核；果核；核心；原子核；细胞核；地核", "ex": "El núcleo familiar es muy importante para mí.", "lvl": "B2"},
{"t": "general", "es": "longitud", "pos": "f.", "zh": "长；长度；[地] 经度", "ex": "La longitud del río es de mil kilómetros.", "lvl": "B2"},
{"t": "general", "es": "utilidad", "pos": "f.", "zh": "用处；好处；收益", "ex": "Esta aplicación nueva tiene mucha utilidad.", "lvl": "B1"},
{"t": "general", "es": "difusión", "pos": "f.", "zh": "传播；扩散", "ex": "La difusión de la noticia fue muy rápida.", "lvl": "B2"},
{"t": "general", "es": "miel", "pos": "f.", "zh": "蜜；(制糖用)糖浆；甜蜜", "ex": "Me gusta el pan con miel en el desayuno.", "lvl": "A2"},
{"t": "general", "es": "comisario", "pos": "m.", "zh": "代表；委员；警察局长", "ex": "El comisario investiga el robo del banco.", "lvl": "B2"},
{"t": "general", "es": "profundidad", "pos": "f.", "zh": "深；(物体的)厚度；深处", "ex": "No conozco la profundidad del mar.", "lvl": "B2"},
{"t": "general", "es": "distinción", "pos": "f.", "zh": "区别；荣誉；卓越", "ex": "No hay distinción entre los dos productos.", "lvl": "B2"},
{"t": "general", "es": "finalidad", "pos": "f.", "zh": "目的；宗旨；用途", "ex": "La finalidad del curso es mejorar el nivel.", "lvl": "B2"},
{"t": "general", "es": "patrón", "pos": "m.", "zh": "f. 保护人；支持者；赞助者；房东；主人；雇主；(小船的)船长；(服装裁剪的)纸样；模式；(货币的)本位", "ex": "Mi patrón me paga cada quincena.", "lvl": "B2"},
{"t": "general", "es": "escándalo", "pos": "m.", "zh": "喧哗；丑事；令人气质的事情", "ex": "La noticia causó un gran escándalo.", "lvl": "B2"},
{"t": "general", "es": "cálculo", "pos": "m.", "zh": "计算；计划；估计；慎重；结石", "ex": "Hice un cálculo rápido del presupuesto.", "lvl": "B1"},
{"t": "general", "es": "magnitud", "pos": "f.", "zh": "大小；数量；重量；长度；重要性；星等(指星的亮度)；量值", "ex": "No imaginamos la magnitud del problema.", "lvl": "B2"},
{"t": "general", "es": "pistola", "pos": "f.", "zh": "手枪；喷枪", "ex": "El policía lleva una pistola en el cinturón.", "lvl": "B1"},
{"t": "general", "es": "moisés", "pos": "m.", "zh": "柳条摇篮", "ex": "El bebé duerme en su moisés.", "lvl": "B2"},
{"t": "general", "es": "traducción", "pos": "f.", "zh": "翻译；译义；(对文本等)解释", "ex": "La traducción de este libro fue difícil.", "lvl": "B1"},
{"t": "general", "es": "sucesión", "pos": "f.", "zh": "连续；连串；继承；子女；后代；遗产", "ex": "Una sucesión de errores arruinó el plan.", "lvl": "B2"},
{"t": "general", "es": "estrato", "pos": "m.", "zh": "层；地层；云层；阶层", "ex": "Los geólogos estudian cada estrato de roca.", "lvl": "B2"},
{"t": "soc", "es": "rango", "pos": "m.", "zh": "等级；身份；社会地位", "ex": "El capitán tiene un rango superior.", "lvl": "B2"},
{"t": "diario", "es": "minoría", "pos": "f.", "zh": "少数；少数派；少数民族；未成年", "ex": "Solo una minoría votó en contra.", "lvl": "B2"},
{"t": "casa", "es": "cobertura", "pos": "f.", "zh": "盖；罩；覆盖物；罩子；床单；受爵仪式；担保(金)", "ex": "La cobertura de internet aquí es mala.", "lvl": "B2"},
{"t": "general", "es": "montero", "pos": "m.", "zh": "猎人", "ex": "El montero cazó un jabalí en el bosque.", "lvl": "B2"},
{"t": "general", "es": "montón", "pos": "m.", "zh": "堆；大量", "ex": "Hay un montón de ropa en la silla.", "lvl": "A2"},
{"t": "general", "es": "suicidio", "pos": "m.", "zh": "自杀(事件)", "ex": "La prevención del suicidio es muy importante.", "lvl": "B2"},
{"t": "general", "es": "pasto", "pos": "m.", "zh": "牧放；牧草；牧场；饲料；养料；材料", "ex": "Las vacas comen pasto en el campo.", "lvl": "B1"},
{"t": "casa", "es": "herramienta", "pos": "f.", "zh": "工具；器具；家什", "ex": "Necesito herramientas para arreglar la mesa.", "lvl": "A2"},
{"t": "emo", "es": "preferencia", "pos": "f.", "zh": "宁愿；偏爱；优先；优惠", "ex": "Doy preferencia a los productos locales.", "lvl": "B1"},
{"t": "viajes", "es": "vuelo", "pos": "m.", "zh": "飞；飞行距离；(飞机) 航程；航班；(翼羽；伸出部分)", "ex": "El vuelo a Madrid sale a las cinco.", "lvl": "B1"},
{"t": "general", "es": "burguesía", "pos": "f.", "zh": "资产阶级；中产阶级", "ex": "La burguesía creció durante el siglo XIX.", "lvl": "B2"},
{"t": "general", "es": "acento", "pos": "m.", "zh": "重音；重音符号；音调；口音", "ex": "Ella habla español con acento mexicano.", "lvl": "B1"},
{"t": "general", "es": "desorden", "pos": "m.", "zh": "杂乱；骚动；失调；放荡", "ex": "Tu habitación está en un gran desorden.", "lvl": "B1"},
{"t": "general", "es": "desempeño", "pos": "m.", "zh": "担任；赎回；能力；本领", "ex": "Su desempeño en el trabajo es excelente.", "lvl": "B2"},
{"t": "general", "es": "absorción", "pos": "f.", "zh": "吸收；专心", "ex": "La absorción de agua es rápida en esta tierra.", "lvl": "B2"},
{"t": "general", "es": "restricción", "pos": "f.", "zh": "限制；约束", "ex": "Hay restricciones de velocidad en esta zona.", "lvl": "B2"},
{"t": "general", "es": "escasez", "pos": "f.", "zh": "缺少；拮据；吝啬", "ex": "La escasez de agua afecta a la región.", "lvl": "B2"},
{"t": "general", "es": "cuaderno", "pos": "m.", "zh": "练习本；笔记本", "ex": "Apunto las palabras en mi cuaderno.", "lvl": "A2"},
{"t": "general", "es": "monasterio", "pos": "m.", "zh": "隐修院；寺院", "ex": "Visitamos un monasterio antiguo en la montaña.", "lvl": "B2"},
{"t": "edu", "es": "privilegio", "pos": "m.", "zh": "特权；优惠；特许；特权(优惠、特许)证书", "ex": "Estudiar aquí es un privilegio.", "lvl": "B2"},
{"t": "general", "es": "utopia", "pos": "f.", "zh": "乌托邦；空想", "ex": "Su plan es una utopía imposible.", "lvl": "B2"},
{"t": "trabajo", "es": "oficio", "pos": "m.", "zh": "职业；工作；公文；书面通知；祈祷", "ex": "El albañil aprendió su oficio de joven.", "lvl": "B1"},
{"t": "general", "es": "disponibilidad", "pos": "f.", "zh": "可利用性；预备役；后补期；pl. 条件；状况", "ex": "Confirmo mi disponibilidad para el jueves.", "lvl": "B2"},
{"t": "general", "es": "acero", "pos": "m.", "zh": "钢；白刃武器；勇气", "ex": "El puente está construido con acero.", "lvl": "B1"},
{"t": "general", "es": "intercambio", "pos": "m.", "zh": "交换；交流", "ex": "Hay un intercambio de estudiantes con Francia.", "lvl": "B1"},
{"t": "general", "es": "sugerencia", "pos": "f.", "zh": "提议；建议；意见", "ex": "¿Tienes alguna sugerencia para el menú?", "lvl": "B1"},
{"t": "general", "es": "callejón", "pos": "m.", "zh": "胡同；小巷", "ex": "El gato entró en un callejón estrecho.", "lvl": "B1"},
{"t": "general", "es": "bolígrafo", "pos": "m.", "zh": "圆珠笔", "ex": "¿Me prestas tu bolígrafo un momento?", "lvl": "A2"},
{"t": "general", "es": "intermediario", "pos": "m.", "zh": "中间人；调解人；中间商；经纪人", "ex": "Vendí la casa sin intermediarios ni comisiones.", "lvl": "B2"},
{"t": "general", "es": "estallido", "pos": "m.", "zh": "爆炸(声)；爆裂(声)；不牵结局；突然完蛋", "ex": "Se oyó un estallido en la calle.", "lvl": "B2"},
{"t": "general", "es": "planeo", "pos": "m.", "zh": "滑翔", "ex": "El águila hace un planeo sobre el valle.", "lvl": "B2"},
{"t": "general", "es": "impacto", "pos": "m.", "zh": "冲击；撞击", "ex": "El impacto de la noticia fue enorme.", "lvl": "B2"},
{"t": "general", "es": "artesania", "pos": "f.", "zh": "手工业；手工艺；手工业品", "ex": "El mercado local vende artesanía tradicional.", "lvl": "B2"},
{"t": "general", "es": "llanura", "pos": "f.", "zh": "平坦；平原；平川", "ex": "La llanura se extiende hasta el horizonte.", "lvl": "B2"},
{"t": "general", "es": "destinatario", "pos": "m.", "zh": "收信人；收件人", "ex": "Escribe el nombre del destinatario en el sobre.", "lvl": "B2"},
{"t": "general", "es": "éxodo", "pos": "m.", "zh": "(大批人的)移居国外；外出；(《圣经》中的)《出埃及记》", "ex": "El éxodo de jóvenes busca mejores oportunidades.", "lvl": "B2"},
{"t": "naturaleza", "es": "plátano", "pos": "m.", "zh": "大蕉树；香蕉树；大蕉；香蕉", "ex": "El plátano es una fruta rica en potasio.", "lvl": "A1"},
{"t": "trabajo", "es": "boom", "pos": "m.", "zh": "(商业等的) 景气；突趋繁荣；激增；暴涨", "ex": "El boom turístico cambió la ciudad.", "lvl": "B2"},
{"t": "general", "es": "élite", "pos": "f.", "zh": "精英；杰出人物；上层人士", "ex": "Los mejores atletas forman la élite.", "lvl": "B2"},
{"t": "soc", "es": "aristocracia", "pos": "f.", "zh": "贵族统治；贵族；上层社会；优秀人物；贵族气派", "ex": "La aristocracia perdió poder en el siglo XX.", "lvl": "B2"},
{"t": "general", "es": "rivalidad", "pos": "f.", "zh": "争夺；竞争；角逐", "ex": "Hay una gran rivalidad entre los dos equipos.", "lvl": "B2"},
{"t": "salud", "es": "propensión", "pos": "f.", "zh": "倾向；爱好；(对某种疾病的)易感染素质", "ex": "Tiene propensión a resfriarse en invierno.", "lvl": "B2"},
{"t": "general", "es": "meseta", "pos": "f.", "zh": "楼梯平台；高原", "ex": "La meseta española está en el centro del país.", "lvl": "B2"},
{"t": "general", "es": "freno", "pos": "m.", "zh": "马嚼子；闸；制动器；约束；制约", "ex": "El freno del coche falló en la cuesta.", "lvl": "B1"},
{"t": "general", "es": "deducción", "pos": "f.", "zh": "推断；演绎；扣除", "ex": "Hice una deducción lógica a partir de los datos.", "lvl": "B2"},
{"t": "comida", "es": "coliflor", "pos": "f.", "zh": "【植】花椰菜；菜花", "ex": "La coliflor es muy saludable para la dieta.", "lvl": "A2"},
{"t": "general", "es": "fideo", "pos": "m.", "zh": "通心粉；面条；干瘦的人", "ex": "Me gusta comer fideos con verduras.", "lvl": "A2"},
{"t": "casa", "es": "coleccionista", "pos": "m.", "zh": "收集人；收藏家", "ex": "Mi tío es un coleccionista de sellos antiguos.", "lvl": "B1"},
{"t": "general", "es": "perseverancia", "pos": "f.", "zh": "坚持；坚忍不拔", "ex": "Su perseverancia la ayudó a aprobar el examen.", "lvl": "B2"},
{"t": "general", "es": "interdependencia", "pos": "f.", "zh": "互相依赖；互相依存", "ex": "La interdependencia económica entre países es evidente.", "lvl": "B2"},
{"t": "general", "es": "bufanda", "pos": "f.", "zh": "围巾；围脖", "ex": "En invierno siempre llevo una bufanda de lana.", "lvl": "A2"},
{"t": "general", "es": "catastro", "pos": "m.", "zh": "地籍册；土地清册", "ex": "El catastro registra todas las propiedades de la ciudad.", "lvl": "B2"},
{"t": "general", "es": "pingüino", "pos": "m.", "zh": "企鹅", "ex": "El pingüino vive en regiones muy frías.", "lvl": "A2"},
{"t": "general", "es": "cabeza", "pos": "f.", "zh": "头；脑袋；上部；前端；主体；头像", "ex": "Me duele la cabeza después del trabajo.", "lvl": "A1"},
{"t": "general", "es": "aprieto", "pos": "m.", "zh": "拥挤；窘迫；困境", "ex": "Estoy en un aprieto porque perdí mi cartera.", "lvl": "B2"},
{"t": "general", "es": "pretérito", "pos": "m.", "zh": "过去；过去时", "ex": "En la clase aprendimos el pretérito indefinido.", "lvl": "B1"},
{"t": "general", "es": "inflexibilidad", "pos": "f.", "zh": "不曲性；不弯性；坚定不移；不屈不挠；毫不动摇", "ex": "Su inflexibilidad ante las reglas sorprendió a todos.", "lvl": "B2"},
{"t": "naturaleza", "es": "florista", "pos": "m.", "zh": "花商；卖花人", "ex": "La florista vende flores frescas cada mañana.", "lvl": "B1"},
{"t": "general", "es": "tarde", "pos": "f.", "zh": "午后；下午；晚；迟", "ex": "Esta tarde voy a visitar a mi abuela.", "lvl": "A1"},
{"t": "naturaleza", "es": "alpinismo", "pos": "m.", "zh": "登山运动", "ex": "El alpinismo exige mucha preparación física.", "lvl": "B1"},
{"t": "naturaleza", "es": "oruga", "pos": "f.", "zh": "毛虫；蠲；履带", "ex": "La oruga se convertirá en una mariposa.", "lvl": "B2"},
{"t": "comida", "es": "catering", "pos": "m.", "zh": "给养；承办酒席；提供饮食及服务", "ex": "El catering del hotel preparó la cena del evento.", "lvl": "B2"},
{"t": "general", "es": "manzana", "pos": "f.", "zh": "苹果；剑柄头；街区；建筑群；喉结；轮毂；球形饰物", "ex": "Como una manzana todos los días.", "lvl": "A1"},
{"t": "general", "es": "pachorra", "pos": "f.", "zh": "怠情；慢性子.", "ex": "Su pachorra me pone nerviosa a veces.", "lvl": "B2"},
{"t": "general", "es": "microsurco", "pos": "m.", "zh": "密纹唱片", "ex": "Encontré un microsurco antiguo en la tienda.", "lvl": "B2"},
{"t": "general", "es": "abarca", "pos": "f.", "zh": "(生皮制成的)凉鞋；木履", "ex": "Las abarcas de cuero son cómodas para caminar.", "lvl": "B2"},
{"t": "salud", "es": "accidente", "pos": "m.", "zh": "意外；事故；发病；高低不平；词形变化", "ex": "Hubo un accidente de coche en la autopista.", "lvl": "A2"},
{"t": "general", "es": "aceituna", "pos": "f.", "zh": "油橄榄", "ex": "Me encanta el aceite hecho de aceitunas.", "lvl": "B1"},
{"t": "general", "es": "acercamiento", "pos": "m.", "zh": "靠近；接近", "ex": "El acercamiento entre los dos países mejora las relaciones.", "lvl": "B1"},
{"t": "general", "es": "actuación", "pos": "f.", "zh": "活动；演出；表示演；pl. 诉讼", "ex": "Su actuación en el teatro fue excelente.", "lvl": "B1"},
{"t": "naturaleza", "es": "agarre", "pos": "m.", "zh": "把手；靠山；借口", "ex": "El agarre de esta maleta está roto.", "lvl": "B2"},
{"t": "general", "es": "agradecimiento", "pos": "m.", "zh": "感激；感谢；感激之情；感恩之情", "ex": "Quiero expresar mi agradecimiento por tu ayuda.", "lvl": "B1"},
{"t": "general", "es": "algoritmos", "pos": "m.", "zh": "算法；规则系统", "ex": "Los algoritmos de la aplicación son muy eficientes.", "lvl": "B2"},
{"t": "general", "es": "amenazas", "pos": "f.", "zh": "威胁；恐吓；威胁性的言行", "ex": "Recibió amenazas anónimas por teléfono ayer.", "lvl": "B1"},
{"t": "general", "es": "apuesta", "pos": "f.", "zh": "打赌；赌注", "ex": "Hicimos una apuesta sobre el resultado del partido.", "lvl": "B2"},
{"t": "general", "es": "aristócratas", "pos": "m.", "zh": "贵族；有贵族派头的人", "ex": "Los aristócratas vivían en grandes palacios.", "lvl": "B2"},
{"t": "general", "es": "arruga", "pos": "f.", "zh": "皱纹；褶子", "ex": "Tiene una arruga cerca del ojo izquierdo.", "lvl": "B2"},
{"t": "general", "es": "atributos", "pos": "m.", "zh": "属性；特性；标志；象征；表语", "ex": "El software muestra los atributos de cada archivo.", "lvl": "B2"},
{"t": "general", "es": "bienes", "pos": "m.", "zh": "pl. 财产", "ex": "El abogado administra los bienes de la familia.", "lvl": "B1"},
{"t": "general", "es": "cara", "pos": "f.", "zh": "脸；面；面容；表情；脸色；脸向；对对", "ex": "Se lavó la cara con agua fría.", "lvl": "A1"},
{"t": "general", "es": "cometido", "pos": "m.", "zh": "任务；委托；职责", "ex": "Cumplió su cometido con mucho éxito.", "lvl": "B2"},
{"t": "general", "es": "corta", "pos": "f.", "zh": "砍伐；短的 (corto 的阴性形式)", "ex": "Esta falda nueva es muy corta.", "lvl": "A2"},
{"t": "general", "es": "costas", "pos": "m.", "zh": "成本；费用；麻醉品；毒品", "ex": "El juez condenó al acusado a pagar las costas.", "lvl": "B1"},
{"t": "general", "es": "códigos", "pos": "m.", "zh": "法典；法规汇编；规则；条例；电码", "ex": "El abogado conoce bien los códigos legales.", "lvl": "B2"},
{"t": "general", "es": "crítica", "pos": "f.", "zh": "评论；批评；非难", "ex": "La crítica del profesor fue muy útil para mí.", "lvl": "B1"},
{"t": "soc", "es": "cuestionarios", "pos": "m.", "zh": "问题表；考题；审讯；调查表", "ex": "Completamos los cuestionarios para el estudio.", "lvl": "B1"},
{"t": "general", "es": "definición", "pos": "f.", "zh": "定义；释义；(电视的) 清晰度；(透镜的) 分辨率", "ex": "Busca la definición de esa palabra en el diccionario.", "lvl": "B1"},
{"t": "general", "es": "descubrimiento", "pos": "m.", "zh": "发现；发明", "ex": "El descubrimiento científico sorprendió a todos.", "lvl": "B1"},
{"t": "general", "es": "deseos", "pos": "f.", "zh": "字母 d 的名称；prep. 表示从属；表示制作材料；表示涉及的事物；表示动作的施行者或对象", "ex": "Mis mejores deseos para tu cumpleaños.", "lvl": "A2"},
{"t": "general", "es": "determinación", "pos": "f.", "zh": "确定；决心；果敢", "ex": "Tomó la determinación de dejar de fumar.", "lvl": "B2"},
{"t": "general", "es": "dinámica", "pos": "f.", "zh": "动力学；力学；动力", "ex": "La dinámica del equipo cambió después de la reunión.", "lvl": "B2"},
{"t": "general", "es": "dios", "pos": "m.", "zh": "上帝；神；偶像；崇拜 物", "ex": "Los antiguos griegos adoraban a muchos dioses.", "lvl": "B1"},
{"t": "edu", "es": "disciplinas", "pos": "f.", "zh": "纪律；教育；课程；鞭答", "ex": "La universidad ofrece varias disciplinas artísticas.", "lvl": "B1"},
{"t": "general", "es": "dividendos", "pos": "m.", "zh": "被除数；股息", "ex": "La empresa repartió dividendos entre los accionistas.", "lvl": "B2"},
{"t": "general", "es": "effectos", "pos": "m.", "zh": "结果；后果；效果；效 应；功效；影响", "ex": "El medicamento produjo efectos secundarios leves.", "lvl": "B1"},
{"t": "general", "es": "empaque", "pos": "m.", "zh": "包装；包装用物；外 貌；装腔作势", "ex": "El empaque del producto es muy bonito.", "lvl": "B2"},
{"t": "general", "es": "envidia", "pos": "f.", "zh": "妒忌；羡慕", "ex": "Siente envidia por el éxito de su amigo.", "lvl": "B1"},
{"t": "salud", "es": "epidemias", "pos": "f.", "zh": "流行病；流行；盛行", "ex": "Las epidemias se propagan rápidamente en invierno.", "lvl": "B2"},
{"t": "general", "es": "especulación", "pos": "f.", "zh": "思索；推测；投机买卖", "ex": "La especulación inmobiliaria subió los precios.", "lvl": "B2"},
{"t": "diario", "es": "estacionalidad", "pos": "f.", "zh": "季节性；季节特点", "ex": "El turismo tiene una clara estacionalidad en esta región.", "lvl": "B2"},
{"t": "general", "es": "estadísticas", "pos": "f.", "zh": "统计学；统计", "ex": "Las estadísticas muestran un aumento de ventas.", "lvl": "B1"},
{"t": "general", "es": "estilos", "pos": "m.", "zh": "文体；文风；风格；方式；形式；作风；式样；类型", "ex": "Me gustan los estilos de música diferentes.", "lvl": "B1"},
{"t": "general", "es": "estratos", "pos": "m.", "zh": "层；地层；云层；阶层", "ex": "La sociedad está formada por diferentes estratos.", "lvl": "B2"},
{"t": "general", "es": "estructura", "pos": "f.", "zh": "结构；构造；机构；组织", "ex": "La estructura del edificio es muy sólida.", "lvl": "B1"},
{"t": "general", "es": "explotación", "pos": "f.", "zh": "开发；利用；剥削", "ex": "La explotación infantil está prohibida por ley.", "lvl": "B2"},
{"t": "general", "es": "fenómenos", "pos": "m.", "zh": "现象；怪物；杰出的人", "ex": "Los fenómenos naturales atraen a los científicos.", "lvl": "B1"},
{"t": "general", "es": "ferrocarriles", "pos": "m.", "zh": "铁路；铁道；列车；铁路运输", "ex": "Los ferrocarriles conectan las ciudades del país.", "lvl": "B1"},
{"t": "general", "es": "finanzas", "pos": "f.", "zh": "pl. 财政；金融；资金", "ex": "Mi hermano estudia finanzas en la universidad.", "lvl": "B2"},
{"t": "general", "es": "fluctuacion", "pos": "f.", "zh": "漂动；波动；浮动；犹豫不决", "ex": "La fluctuación del precio afecta a la economía.", "lvl": "B2"},
{"t": "general", "es": "flujos", "pos": "m.", "zh": "流动；流出；流出物；涨潮", "ex": "Los flujos de dinero circulan por el mercado.", "lvl": "B2"},
{"t": "tec", "es": "fotografía", "pos": "f.", "zh": "照片；相片；摄影技术；摄影；拍照；摄影室", "ex": "Esta fotografía fue tomada en Madrid.", "lvl": "A2"},
{"t": "general", "es": "fragmentación", "pos": "f.", "zh": "分为碎块；碎片", "ex": "La fragmentación del territorio complica el transporte.", "lvl": "B2"},
{"t": "comida", "es": "fruta", "pos": "f.", "zh": "水果", "ex": "Me gusta comer fruta después de la cena.", "lvl": "A1"},
{"t": "general", "es": "fuerza", "pos": "f.", "zh": "力；动力；效力；武力", "ex": "El atleta mostró mucha fuerza en la competencia.", "lvl": "A2"},
{"t": "general", "es": "fuerzas", "pos": "f.", "zh": "力；动力；效力；武力", "ex": "Recuperó todas sus fuerzas después de descansar.", "lvl": "A2"},
{"t": "general", "es": "galería", "pos": "f.", "zh": "走廊；画廊；画集；(剧场)顶层楼座；地道；观众", "ex": "La galería de arte abre los fines de semana.", "lvl": "B1"},
{"t": "general", "es": "gama", "pos": "f.", "zh": "雌雌角鹿；音阶；色域", "ex": "La tienda ofrece una amplia gama de productos.", "lvl": "B2"},
{"t": "general", "es": "gladiadores", "pos": "m.", "zh": "(古罗马的)斗士", "ex": "Los gladiadores luchaban en la arena romana.", "lvl": "B2"},
{"t": "comida", "es": "golosina", "pos": "f.", "zh": "好吃的东西；想望；嘴馋；华而不实的东西", "ex": "Los niños quieren comer golosinas después de la escuela.", "lvl": "B1"},
{"t": "general", "es": "gorra", "pos": "f.", "zh": "帽子；便帽", "ex": "Lleva una gorra para protegerse del sol.", "lvl": "A2"},
{"t": "diario", "es": "hibernación", "pos": "f.", "zh": "冬眠；蛰伏；人工冬眠疗法", "ex": "Los osos pasan el invierno en hibernación.", "lvl": "B2"},
{"t": "emo", "es": "hombres", "pos": "m.", "zh": "人；男子；成年人；男子汉；丈夫；(表示惊讶)好家伙", "ex": "Esos hombres trabajan en la fábrica.", "lvl": "A1"},
{"t": "general", "es": "hostelería", "pos": "f.", "zh": "旅馆业", "ex": "Trabaja en el sector de la hostelería.", "lvl": "B2"},
{"t": "general", "es": "huelga", "pos": "f.", "zh": "空暇；罢工；(土地的)休耕期", "ex": "Los trabajadores iniciaron una huelga por el salario.", "lvl": "B1"},
{"t": "general", "es": "impuestos", "pos": "m.", "zh": "税；捐税", "ex": "Este año pagamos muchos impuestos al Estado.", "lvl": "B1"},
{"t": "trabajo", "es": "industriales", "pos": "f.", "zh": "工业；行业；工厂；技能", "ex": "Varios industriales invirtieron en nuevas fábricas.", "lvl": "B1"},
{"t": "general", "es": "infraestructuras", "pos": "f.", "zh": "基础；基础结构；底层结构", "ex": "Las infraestructuras del país necesitan mejoras.", "lvl": "B2"},
{"t": "edu", "es": "ingresos", "pos": "m.", "zh": "走入；走进；入口；加入；进入；参加仪式；入学考试；存款；收入", "ex": "Sus ingresos mensuales son suficientes para vivir.", "lvl": "B1"},
{"t": "general", "es": "integración", "pos": "f.", "zh": "结合；一体化；积分(法)", "ex": "La integración de los inmigrantes es importante.", "lvl": "B2"},
{"t": "general", "es": "intermediarios", "pos": "m.", "zh": "中间人；调解人；中间商；经纪人", "ex": "Los intermediarios cobran una comisión por la venta.", "lvl": "B2"},
{"t": "viajes", "es": "itinerarios", "pos": "m.", "zh": "旅程；路线；行程；游览图；旅行指南", "ex": "El agente preparó varios itinerarios para el viaje.", "lvl": "B1"},
{"t": "general", "es": "jueces", "pos": "m.", "zh": "法官；审判官；仲裁人；裁断人；裁判员；评判员", "ex": "Los jueces decidieron el caso con justicia.", "lvl": "B1"},
{"t": "naturaleza", "es": "laca", "pos": "f.", "zh": "虫胶；漆；漆器", "ex": "La laca protege la madera de los muebles.", "lvl": "B2"},
{"t": "general", "es": "líderes", "pos": "m.", "zh": "f. 领袖；领先者", "ex": "Los líderes políticos firmaron el acuerdo.", "lvl": "B1"},
{"t": "general", "es": "luchas", "pos": "f.", "zh": "角斗；摔跤；斗争；奋斗；争论", "ex": "La película muestra las luchas de la resistencia.", "lvl": "B1"},
{"t": "general", "es": "masas", "pos": "f.", "zh": "面团；群众；总体", "ex": "El discurso emocionó a las masas.", "lvl": "B1"},
{"t": "general", "es": "masificación", "pos": "f.", "zh": "大众化；拥挤", "ex": "La masificación del turismo daña la ciudad.", "lvl": "B2"},
{"t": "trabajo", "es": "mercados", "pos": "m.", "zh": "集市；市场；商场；链路", "ex": "Los mercados internacionales abren muy temprano.", "lvl": "B1"},
{"t": "general", "es": "mercancías", "pos": "f.", "zh": "贸易；商品；货物", "ex": "El camión transporta mercancías entre las ciudades.", "lvl": "B1"},
{"t": "general", "es": "miembros", "pos": "m.", "zh": "肢体；部分；成员", "ex": "Todos los miembros del equipo asistieron a la reunión.", "lvl": "B1"},
{"t": "general", "es": "modelos", "pos": "m.", "zh": "模本；模范；型号；模特", "ex": "La empresa presentó nuevos modelos de coche.", "lvl": "B1"},
{"t": "edu", "es": "movimiento", "pos": "m.", "zh": "移动；摇动；活动；动作；(物体的) 运动；(资金、人员的) 流动；(政治、社会、思想等方面的运动；(某一时期文学艺术的) 流派；变动", "ex": "El movimiento ecologista crece cada año.", "lvl": "B1"},
{"t": "naturaleza", "es": "niveles", "pos": "m.", "zh": "水平面；水平线；水平仪；高度；水平；标准；级别", "ex": "El examen tiene varios niveles de dificultad.", "lvl": "B1"},
{"t": "general", "es": "ostentación", "pos": "f.", "zh": "显示；炫耀", "ex": "Compró el coche por pura ostentación.", "lvl": "B2"},
{"t": "general", "es": "pie", "pos": "m.", "zh": "足；脚；蹄；爪；(鞋、袜等的) 脚部；鞋底", "ex": "Se lastimó el pie jugando al fútbol.", "lvl": "A1"},
{"t": "general", "es": "placer", "pos": "m.", "zh": "愉快；娱乐；享乐；使愉快；使高兴", "ex": "Hoy fue un gran placer conocerte.", "lvl": "B1"},
{"t": "trabajo", "es": "plaza", "pos": "f.", "zh": "广场；要塞；市场；地方；职位", "ex": "La plaza mayor está llena de gente.", "lvl": "A2"},
{"t": "tec", "es": "procedimiento", "pos": "m.", "zh": "方法；过程；程序；手续", "ex": "Sigue el procedimiento correcto para solicitar el permiso.", "lvl": "B1"},
{"t": "soc", "es": "pueblos", "pos": "m.", "zh": "村镇；人民；平民；居民；民族", "ex": "Visitamos varios pueblos pequeños durante el viaje.", "lvl": "A2"},
{"t": "casa", "es": "puerta", "pos": "f.", "zh": "门；门路；入境税；球门", "ex": "Por favor, cierra la puerta al salir.", "lvl": "A1"},
{"t": "general", "es": "quejas", "pos": "f.", "zh": "呻吟；叫苦；怨言；不满；告状", "ex": "El cliente presentó quejas sobre el servicio.", "lvl": "B1"},
{"t": "general", "es": "recogida", "pos": "f.", "zh": "拾起；收起；收集", "ex": "La recogida de basura ocurre cada mañana.", "lvl": "B1"},
{"t": "trabajo", "es": "recreación", "pos": "f.", "zh": "再创造；再创作；(工作之余的)休息", "ex": "El parque ofrece áreas de recreación para los niños.", "lvl": "B1"},
{"t": "diario", "es": "renta", "pos": "f.", "zh": "收益；年金；租金；公债；公债券；捐税", "ex": "La renta de este piso es muy cara.", "lvl": "B1"},
{"t": "diario", "es": "rentas", "pos": "f.", "zh": "收益；年金；租金；公债；公债券；捐税", "ex": "Las rentas de sus propiedades le dan estabilidad.", "lvl": "B1"},
{"t": "tec", "es": "retroalimentación", "pos": "f.", "zh": "(信息) 反馈", "ex": "La retroalimentación del profesor mejora mi trabajo.", "lvl": "B2"},
{"t": "general", "es": "revuelta", "pos": "f.", "zh": "旋转；骚动；争吵；拐角", "ex": "La revuelta comenzó en la plaza central.", "lvl": "B2"},
{"t": "trabajo", "es": "saturación", "pos": "f.", "zh": "饱和(状态)；(市场的)饱和(状态)", "ex": "La saturación del mercado reduce los beneficios.", "lvl": "B2"},
{"t": "general", "es": "sea", "pos": "m.", "zh": "本质；实体；是；存在；发生；进行；aux. 被；由", "ex": "Es importante que sea puntual a la reunión.", "lvl": "A2"},
{"t": "general", "es": "será", "pos": "m.", "zh": "本质；实体；是；存在；发生；进行；aux. 被；由", "ex": "Mañana será un día importante para nosotros.", "lvl": "A2"},
{"t": "general", "es": "sindicatos", "pos": "m.", "zh": "工会；辛迪加；企业联合会会", "ex": "Los sindicatos negociaron un nuevo contrato.", "lvl": "B2"},
{"t": "general", "es": "sino", "pos": "m.", "zh": "命运；记号；而是；除...之外；中国的", "ex": "No es un problema sino una oportunidad.", "lvl": "B1"},
{"t": "soc", "es": "sociólogos", "pos": "m.", "zh": "社会学者", "ex": "Los sociólogos analizan el comportamiento humano.", "lvl": "B2"},
{"t": "general", "es": "sol", "pos": "m.", "zh": "太阳；阳光；索尔(秘鲁货币单位)", "ex": "El sol brilla fuerte hoy en la playa.", "lvl": "A1"},
{"t": "general", "es": "tortura", "pos": "f.", "zh": "拷打；痛苦；歪；斜", "ex": "La tortura está prohibida por la ley internacional.", "lvl": "B2"},
{"t": "viajes", "es": "trenes", "pos": "m.", "zh": "火车；成套物品；行李；籀重；排场", "ex": "Los trenes salen cada media hora de la estación.", "lvl": "A1"},
{"t": "viajes", "es": "turoperadores", "pos": "m.", "zh": "旅行社", "ex": "Los turoperadores organizan viajes a la playa.", "lvl": "B2"},
{"t": "general", "es": "unidades", "pos": "f.", "zh": "单一性；个体；单元；单位；统一；团结", "ex": "El curso tiene diez unidades de aprendizaje.", "lvl": "B1"},
{"t": "viajes", "es": "urbes", "pos": "f.", "zh": "大城市；大都市", "ex": "Las grandes urbes atraen a millones de personas.", "lvl": "B2"},
{"t": "general", "es": "utilización", "pos": "f.", "zh": "使用；利用", "ex": "La utilización de internet crece cada año.", "lvl": "B1"},
{"t": "trabajo", "es": "ventas", "pos": "f.", "zh": "卖；出让；销售量；(路边)客栈", "ex": "Las ventas de verano superaron las expectativas.", "lvl": "B1"},
{"t": "general", "es": "vertiente", "pos": "m./f.", "zh": "斜坡；坡地；坡面", "ex": "La vertiente norte de la montaña tiene más nieve.", "lvl": "B2"},
{"t": "viajes", "es": "visados", "pos": "m.", "zh": "签证(西班牙)；签发的", "ex": "Los visados de estudiante se tramitan en la embajada.", "lvl": "B1"},
{"t": "general", "es": "visitas", "pos": "f.", "zh": "访问；参观；客人；来访者；监狱巡视厅", "ex": "Las visitas al museo son gratuitas los domingos.", "lvl": "A2"},
{"t": "naturaleza", "es": "vista", "pos": "f.", "zh": "视觉；看；目光；视线；视野；海关检查员", "ex": "Desde aquí hay una vista magnífica del valle.", "lvl": "A2"},
{"t": "general", "es": "personal", "pos": "adj.", "zh": "个人的；私人的；单人的；亲自的；[集]人员；职工", "ex": "Esa decisión es personal y solo me afecta a mí.", "lvl": "A2"},
{"t": "emo", "es": "triste", "pos": "adj.", "zh": "悲伤的；忧伤的；凄凉的；悲惨的；阴暗的", "ex": "Ella se siente triste porque extraña a su familia.", "lvl": "A2"},
{"t": "naturaleza", "es": "gris", "pos": "adj.", "zh": "灰色的；平淡的；乏味的；阴沉的（天气）；抑郁的（性情）；灰色", "ex": "Hoy el cielo está gris y va a llover.", "lvl": "A1"},
{"t": "general", "es": "inteligente", "pos": "adj.", "zh": "聪明的；有才智的；聪明人", "ex": "Mi hermana es muy inteligente y siempre saca buenas notas.", "lvl": "A2"},
{"t": "general", "es": "serio", "pos": "adj.", "zh": "严肃的；认真的；当真的；严重的；令人担心的；重要的", "ex": "Mi profesor es serio, pero explica muy bien.", "lvl": "A2"},
{"t": "general", "es": "tranquilo", "pos": "adj.", "zh": "平静的；安静的；宁静的；镇静的；漫不经心的", "ex": "Este barrio es tranquilo y seguro por la noche.", "lvl": "A2"},
{"t": "naturaleza", "es": "gordo", "pos": "adj.", "zh": "肥胖的；肥的；多脂肪的；厚的；粗的；头等的；(动物)脂肪；(彩票)光彩", "ex": "El gato de mi vecino es muy gordo.", "lvl": "A2"},
{"t": "emo", "es": "amable", "pos": "adj.", "zh": "可爱的；亲切的；和蔼可亲的", "ex": "La dependienta fue muy amable con nosotros.", "lvl": "A1"},
{"t": "viajes", "es": "viajero", "pos": "adj.", "zh": "旅行的；【动】徒居的；旅客；旅行家", "ex": "El viajero perdió su equipaje en el aeropuerto.", "lvl": "A2"},
{"t": "general", "es": "abierto", "pos": "adj.", "zh": "打开着的；开阔的；敞开着的；坦率的", "ex": "El museo está abierto todos los lunes.", "lvl": "A1"},
{"t": "general", "es": "optimista", "pos": "adj.", "zh": "乐观的；乐观主义的；乐观主义者", "ex": "A pesar de todo, mi abuela sigue siendo optimista.", "lvl": "B1"},
{"t": "general", "es": "nuevo", "pos": "adj.", "zh": "新的；未旧的；新人；新手；新成员", "ex": "Me compré un teléfono nuevo la semana pasada.", "lvl": "A1"},
{"t": "general", "es": "frío", "pos": "adj.", "zh": "冷的；凉的；寒冷的；严寒的；冷；凉；寒冷；严寒", "ex": "Hace mucho frío en invierno en mi ciudad.", "lvl": "A1"},
{"t": "general", "es": "alto", "pos": "adj.", "zh": "高的；响亮的；崇高的；地位高的；高度；高地；在上面；高声地；站住", "ex": "Mi hermano es más alto que yo.", "lvl": "A1"},
{"t": "general", "es": "simpático", "pos": "adj.", "zh": "同情的；使人有好感的；可亲的", "ex": "Mi nuevo compañero es muy simpático.", "lvl": "A2"},
{"t": "general", "es": "generoso", "pos": "adj.", "zh": "高尚的；慷慨的；优秀的；大量的；丰富的", "ex": "Mi tío es muy generoso con su dinero.", "lvl": "B1"},
{"t": "general", "es": "oficial", "pos": "adj.", "zh": "官方的；正式的；职员；军官；工人", "ex": "El idioma oficial de España es el español.", "lvl": "B1"},
{"t": "general", "es": "guapo", "pos": "adj.", "zh": "漂亮的；好看的；勇敢的；f.帅哥；美女", "ex": "El novio de Marta es muy guapo.", "lvl": "A2"},
{"t": "general", "es": "superior", "pos": "adj.", "zh": "上部的；上端的；高级的；出众的；f.负责人；上级", "ex": "La calidad de este producto es superior a la del otro.", "lvl": "B1"},
{"t": "diario", "es": "viejo", "pos": "adj.", "zh": "老的；年老的；陈旧的；古老的；老人", "ex": "Mi abuelo tiene un perro muy viejo.", "lvl": "A1"},
{"t": "general", "es": "propio", "pos": "adj.", "zh": "自己的；固有的；特有的；本来的", "ex": "Cada persona tiene su propio estilo de vida.", "lvl": "A2"},
{"t": "general", "es": "real", "pos": "adj.", "zh": "真的；真正的；真实的；王室的", "ex": "¿Es real esta historia que me cuentas?", "lvl": "A2"},
{"t": "general", "es": "correspondal", "pos": "adj.", "zh": "-s. 通信的；通信人；通讯的；报导的；报导员；通讯员", "ex": "El correspondal escribió un artículo sobre el conflicto.", "lvl": "B2"},
{"t": "general", "es": "contento", "pos": "adj.", "zh": "高兴的；满意的；高兴", "ex": "Estoy muy contento con mi nuevo trabajo.", "lvl": "A2"},
{"t": "general", "es": "suficiente", "pos": "adj.", "zh": "充足的；有才能的；自满的", "ex": "Tenemos tiempo suficiente para llegar al cine.", "lvl": "A2"},
{"t": "tec", "es": "técnico", "pos": "adj.", "zh": "技术的；专家；技师；技术人员", "ex": "El problema técnico ya está resuelto.", "lvl": "B1"},
{"t": "general", "es": "cualquiera", "pos": "adj.", "zh": "-pron. indet. 任何一个", "ex": "Puedes elegir cualquiera de estos libros.", "lvl": "A2"},
{"t": "general", "es": "verdadero", "pos": "adj.", "zh": "真实的；确实的；真正的；真诚的", "ex": "Esa película está basada en un hecho verdadero.", "lvl": "B1"},
{"t": "general", "es": "fundamental", "pos": "adj.", "zh": "基础的；基本的；根本的", "ex": "El agua es fundamental para la vida.", "lvl": "B1"},
{"t": "general", "es": "competidor", "pos": "adj.", "zh": "-s. 竞争的；竞争者；对手", "ex": "Nuestro competidor lanzó un producto más barato.", "lvl": "B1"},
{"t": "general", "es": "inferior", "pos": "adj.", "zh": "下方的；差的；少的；下级的；f. 部下；下级", "ex": "La calidad de este teléfono es inferior a la del otro.", "lvl": "B1"},
{"t": "general", "es": "absoluto", "pos": "adj.", "zh": "绝对的；专制的；纯的；完全的；独立的", "ex": "El silencio era absoluto en la biblioteca.", "lvl": "B1"},
{"t": "general", "es": "útil", "pos": "adj.", "zh": "有用的；能用的；有效的；用途；益处；用具；工具", "ex": "Este diccionario es muy útil para aprender español.", "lvl": "A2"},
{"t": "general", "es": "amplio", "pos": "adj.", "zh": "宽敞的；辽阔的；广泛的；宽阔的", "ex": "Su casa tiene un salón muy amplio.", "lvl": "B1"},
{"t": "general", "es": "nervioso", "pos": "adj.", "zh": "神经的；神经质的；紧张不安的；多叶脉的", "ex": "Estoy nervioso porque tengo un examen mañana.", "lvl": "B1"},
{"t": "general", "es": "editorial", "pos": "adj.", "zh": "出版的；编辑的；社论；出版社", "ex": "El diario publicó un editorial sobre la crisis.", "lvl": "B2"},
{"t": "general", "es": "moreno", "pos": "adj.", "zh": "褐色的；棕色的；黝黑的；(白种人中)皮肤黝黑的；黑发的；黑种的；f. 黑种人", "ex": "El chico nuevo de clase es moreno y alto.", "lvl": "A2"},
{"t": "general", "es": "relativo", "pos": "adj.", "zh": "有关联的；相应的；相对(性)的；有限的；表示关系的；关系词", "ex": "El éxito es un concepto relativo para cada persona.", "lvl": "B1"},
{"t": "general", "es": "católico", "pos": "adj.", "zh": "普遍的；天主教的；信奉天主教的；确实的；可信的；天主教教徒", "ex": "Mi abuelo es católico y va a la iglesia los domingos.", "lvl": "B1"},
{"t": "general", "es": "rubio", "pos": "adj.", "zh": "金黄色的；(人)金黄色头发的；金黄色头发的人", "ex": "El niño rubio juega en el parque.", "lvl": "A2"},
{"t": "general", "es": "heroico", "pos": "adj.", "zh": "英雄的；英勇的；歌颂英雄的；史诗的", "ex": "Los bomberos hicieron un esfuerzo heroico para salvar al niño.", "lvl": "B2"},
{"t": "salud", "es": "específico", "pos": "adj.", "zh": "特有的；特定的；具体的；(症状) 特殊的；有特效的；特效药", "ex": "Necesito un ejemplo específico para entenderlo mejor.", "lvl": "B1"},
{"t": "general", "es": "obrero", "pos": "adj.", "zh": "工人的；劳工的；f. 工人", "ex": "El obrero trabaja ocho horas al día.", "lvl": "A2"},
{"t": "soc", "es": "sujeto", "pos": "adj.", "zh": "受支配的；有待于...的；问题；主题；人(泛指)；主体；自我；主语", "ex": "El sujeto de esta oración es el protagonista.", "lvl": "B1"},
{"t": "general", "es": "integral", "pos": "adj.", "zh": "整个的；全部的；构成整体的；积分的；积分", "ex": "El gobierno busca una solución integral para la crisis.", "lvl": "B2"},
{"t": "general", "es": "consumidor", "pos": "adj.", "zh": "消费的；f. 消费者", "ex": "El consumidor debe conocer sus derechos.", "lvl": "B1"},
{"t": "general", "es": "excepcional", "pos": "adj.", "zh": "例外的；罕见的；特别的", "ex": "El equipo hizo un trabajo excepcional este año.", "lvl": "B2"},
{"t": "general", "es": "inocente", "pos": "adj.", "zh": "无幸的；无罪的；善意的；单纯的；无害的；f. 儿童；孩子", "ex": "El juez dijo que el acusado es inocente.", "lvl": "B1"},
{"t": "general", "es": "fantasma", "pos": "adj.", "zh": "虚构的；不可信的；无人居住的；弃置不用的；幻觉；幽灵；自负的人；(图像的)重像", "ex": "Los niños creen que hay un fantasma en la casa.", "lvl": "B2"},
{"t": "general", "es": "celta", "pos": "adj.", "zh": "凯尔特人的；f. 凯尔特人；凯尔特语", "ex": "La música celta me recuerda a Irlanda.", "lvl": "B2"},
{"t": "general", "es": "cruel", "pos": "adj.", "zh": "残忍的；残酷的；严酷的", "ex": "No seas cruel con los animales.", "lvl": "B1"},
{"t": "emo", "es": "patriota", "pos": "adj.", "zh": "爱国的；f. 爱国者", "ex": "Ese soldado es un verdadero patriota.", "lvl": "B2"},
{"t": "general", "es": "energético", "pos": "adj.", "zh": "能量的；能源的", "ex": "El sector energético está cambiando mucho.", "lvl": "B2"},
{"t": "general", "es": "ajeno", "pos": "adj.", "zh": "别人的；陌生的；没有参与...的；对...一无所知；没有...的", "ex": "No quiero meterme en un asunto ajeno.", "lvl": "B1"},
{"t": "general", "es": "magnífico", "pos": "adj.", "zh": "壮丽的；宏伟的；尊敬的；极好的", "ex": "El concierto de anoche fue magnífico.", "lvl": "B1"},
{"t": "general", "es": "argelino", "pos": "adj.", "zh": "阿尔及尔的；阿尔及利亚的；阿尔及尔人；阿尔及利亚人", "ex": "Mi compañero de piso es argelino.", "lvl": "B2"},
{"t": "general", "es": "cuerdo", "pos": "adj.", "zh": "-s. 理智的；明智的；理智的人；明智的人", "ex": "Nadie cuerdo haría ese viaje en esas condiciones.", "lvl": "B2"},
{"t": "general", "es": "infinito", "pos": "adj.", "zh": "无限的；无穷的；极大的；巨大的；无数的；无限；无际；无穷大符号 (∞)；很；非常；极其", "ex": "El amor de una madre es infinito.", "lvl": "B2"},
{"t": "general", "es": "oculto", "pos": "adj.", "zh": "隐藏的；秘密的", "ex": "El tesoro estaba oculto detrás de la montaña.", "lvl": "B2"},
{"t": "general", "es": "coherente", "pos": "adj.", "zh": "连贯的；内聚的；相干的", "ex": "Su explicación fue coherente y convincente.", "lvl": "B2"},
{"t": "general", "es": "importante", "pos": "adj.", "zh": "重大的；重要的", "ex": "La salud es más importante que el dinero.", "lvl": "A2"},
{"t": "general", "es": "articular", "pos": "adj.", "zh": "关节的；连接；清晰地发(音)；分成条款；询问；审问", "ex": "Tiene un problema articular en la rodilla.", "lvl": "B2"},
{"t": "general", "es": "reflexivo", "pos": "adj.", "zh": "反射的；有反射作用的；动脑筋的；经过思考的；自复的", "ex": "Mi jefe es muy reflexivo antes de tomar decisiones.", "lvl": "B2"},
{"t": "naturaleza", "es": "riguroso", "pos": "adj.", "zh": "严厉的；(气候)严酷的；冷酷的；精确的", "ex": "El entrenador es muy riguroso con los jugadores.", "lvl": "B2"},
{"t": "general", "es": "sensacional", "pos": "adj.", "zh": "可以感觉的；引起轰动的；极好的", "ex": "El partido de fútbol de anoche fue sensacional.", "lvl": "B2"},
{"t": "general", "es": "estratégico", "pos": "adj.", "zh": "战略的；重要的；懂得策略的", "ex": "El mercado asiático es estratégico para nuestra empresa.", "lvl": "B2"},
{"t": "general", "es": "exigente", "pos": "adj.", "zh": "要求高的；苛求的；无理要求的", "ex": "Mi profesora de inglés es muy exigente.", "lvl": "B1"},
{"t": "general", "es": "tímido", "pos": "adj.", "zh": "胆怯的；羞怯的", "ex": "Mi hermano es tímido con las personas nuevas.", "lvl": "B1"},
{"t": "naturaleza", "es": "espontáneo", "pos": "adj.", "zh": "自发的；自愿的；(植物)自生的", "ex": "Su aplauso fue espontáneo al terminar el discurso.", "lvl": "B2"},
{"t": "general", "es": "irracional", "pos": "adj.", "zh": "无理性的；不合理的；无理的", "ex": "Esa decisión me parece completamente irracional.", "lvl": "B2"},
{"t": "edu", "es": "suspenso", "pos": "adj.", "zh": "悬挂着的；吊着的；暂停的；中止的；考试不及格的；惊呆的；愕住的；不及格分数", "ex": "El profesor dejó suspenso a media clase.", "lvl": "B2"},
{"t": "general", "es": "sinónimo", "pos": "adj.", "zh": "同义的；同义词", "ex": "Alegría es sinónimo de felicidad en español.", "lvl": "B1"},
{"t": "general", "es": "incipiente", "pos": "adj.", "zh": "开始的；刚出现的；早期的", "ex": "Su negocio es incipiente pero tiene futuro.", "lvl": "B2"},
{"t": "naturaleza", "es": "castano", "pos": "adj.", "zh": "栗色的；栗色；栗树", "ex": "Lleva un abrigo castano en invierno.", "lvl": "B1"},
{"t": "general", "es": "analítico", "pos": "adj.", "zh": "分析的；分解的；解析的", "ex": "El informe analítico explica los resultados del estudio.", "lvl": "B2"},
{"t": "salud", "es": "pulmonar", "pos": "adj.", "zh": "肺的", "ex": "Tiene una infección pulmonar y está en el hospital.", "lvl": "B2"},
{"t": "general", "es": "insular", "pos": "adj.", "zh": "岛屿的；岛上居民", "ex": "El clima insular es más suave que el continental.", "lvl": "B2"},
{"t": "general", "es": "respiratorio", "pos": "adj.", "zh": "呼吸的", "ex": "El ejercicio fortalece el sistema respiratorio.", "lvl": "B2"},
{"t": "general", "es": "formativo", "pos": "adj.", "zh": "形成的；用以构成的", "ex": "El curso formativo de cocina empieza en enero.", "lvl": "B2"},
{"t": "general", "es": "exhaustivo", "pos": "adj.", "zh": "(论述等)全面的；详尽的", "ex": "El médico hizo un examen exhaustivo del paciente.", "lvl": "B2"},
{"t": "general", "es": "despierto", "pos": "adj.", "zh": "醒着的；机灵的", "ex": "A las seis de la mañana ya estaba despierto.", "lvl": "A2"},
{"t": "trabajo", "es": "ferroviario", "pos": "adj.", "zh": "铁路的；铁道的；铁路员工", "ex": "El sistema ferroviario conecta todas las ciudades.", "lvl": "B1"},
{"t": "general", "es": "longitudinal", "pos": "adj.", "zh": "纵向的；经度的", "ex": "El estudio longitudinal siguió a los niños durante diez años.", "lvl": "B2"},
{"t": "general", "es": "arduo", "pos": "adj.", "zh": "艰难的；艰巨的", "ex": "Preparar el examen fue un trabajo arduo.", "lvl": "B2"},
{"t": "general", "es": "cognitivo", "pos": "adj.", "zh": "认识的", "ex": "Los juegos ayudan al desarrollo cognitivo de los niños.", "lvl": "B2"},
{"t": "general", "es": "extraterrestre", "pos": "adj.", "zh": "地球外的；宇宙的；地球外生物；外星人", "ex": "La película cuenta la historia de un extraterrestre amable.", "lvl": "B2"},
{"t": "emo", "es": "indeseable", "pos": "adj.", "zh": "s. 不受喜欢的；不受欢迎的；不受喜欢的人；不受欢迎的人", "ex": "Esa actitud es indeseable en el trabajo.", "lvl": "B2"},
{"t": "general", "es": "subsiguiente", "pos": "adj.", "zh": "随后的；紧接着的", "ex": "En el día subsiguiente, todo volvió a la normalidad.", "lvl": "B2"},
{"t": "viajes", "es": "excursionista", "pos": "adj.", "zh": "郊游的；远足者；旅行者；喜欢郊游的入；喜欢远足的人", "ex": "El excursionista llevó agua y comida para el camino.", "lvl": "B1"},
{"t": "general", "es": "conmovedor", "pos": "adj.", "zh": "震动的；令人激动的", "ex": "Su discurso fue muy conmovedor para todos.", "lvl": "B2"},
{"t": "general", "es": "antipático", "pos": "adj.", "zh": "令人反感的；惹人讨厌的", "ex": "El camarero fue muy antipático con nosotros.", "lvl": "B1"},
{"t": "general", "es": "afirmativo", "pos": "adj.", "zh": "肯定的", "ex": "El resultado del examen fue afirmativo.", "lvl": "B2"},
{"t": "general", "es": "siderúrgico", "pos": "adj.", "zh": "钢铁工业的", "ex": "El grupo siderúrgico compró una nueva fábrica.", "lvl": "B2"},
{"t": "general", "es": "biográfico", "pos": "adj.", "zh": "传记的", "ex": "Leí un libro biográfico sobre un famoso pintor.", "lvl": "B2"},
{"t": "general", "es": "resuelto", "pos": "adj.", "zh": "坚定的；果断的；利落的", "ex": "El capitán fue resuelto en su decisión.", "lvl": "B2"},
{"t": "naturaleza", "es": "creciente", "pos": "adj.", "zh": "成长中的；生长中的；增长着的；河水上涨；酵母", "ex": "El interés por aprender español es creciente en Asia.", "lvl": "B1"},
{"t": "general", "es": "emprendedor", "pos": "adj.", "zh": "有进取心的；敢闯的", "ex": "Mi primo es muy emprendedor y tiene su propia empresa.", "lvl": "B2"},
{"t": "general", "es": "boquiabierto", "pos": "adj.", "zh": "张着嘴的", "ex": "Me quedé boquiabierto al ver el resultado.", "lvl": "B2"},
{"t": "naturaleza", "es": "juguetón", "pos": "adj.", "zh": "贪玩的；爱玩耍的；海气的；顽皮的", "ex": "El cachorro es muy juguetón y travieso.", "lvl": "B1"},
{"t": "general", "es": "dependiente", "pos": "adj.", "zh": "依赖的；从属的；售货员", "ex": "El dependiente me ayudó a encontrar la talla.", "lvl": "B1"},
{"t": "general", "es": "cautivador", "pos": "adj.", "zh": "有魅力的；迷人的", "ex": "Su voz tiene un encanto cautivador.", "lvl": "B2"},
{"t": "general", "es": "escapista", "pos": "adj.", "zh": "逃避现实的；f. 逃避现实者", "ex": "La película escapista nos ayudó a olvidar los problemas.", "lvl": "B2"},
{"t": "general", "es": "activos", "pos": "adj.", "zh": "活跃的；积极的；在活动中的；现行的；速效的；现役的；在职的；资产", "ex": "Los niños activos necesitan mucho ejercicio.", "lvl": "B1"},
{"t": "general", "es": "adecuadas", "pos": "adj.", "zh": "适当的；适合的", "ex": "Usamos las herramientas adecuadas para este trabajo.", "lvl": "B1"},
{"t": "general", "es": "agresiva", "pos": "adj.", "zh": "侵略的；挑衅的；好斗的", "ex": "Su actitud agresiva asustó a los clientes.", "lvl": "B2"},
{"t": "general", "es": "ajenas", "pos": "adj.", "zh": "别人的；陌生的；没有参与...的；对...无所知；没有...的", "ex": "Las opiniones ajenas no me importan demasiado.", "lvl": "B1"},
{"t": "general", "es": "antiguos", "pos": "adj.", "zh": "古代的；古老的；旧的；过时的；资格老的；老成员；古人", "ex": "Me interesan los objetos antiguos de este museo.", "lvl": "B1"},
{"t": "general", "es": "artesanos", "pos": "adj.", "zh": "手工艺的；手艺人", "ex": "Los artesanos del pueblo venden sus productos en el mercado.", "lvl": "B1"},
{"t": "general", "es": "atractivos", "pos": "adj.", "zh": "有吸引力的；有魅力的；魅力；诱惑力；姿色", "ex": "Los precios atractivos de la tienda llaman la atención.", "lvl": "B1"},
{"t": "general", "es": "balnearios", "pos": "adj.", "zh": "沐浴的；浴疗的；浴场；温泉疗养地", "ex": "Los balnearios del norte son famosos por sus aguas.", "lvl": "B2"},
{"t": "general", "es": "bastante", "pos": "adj.", "zh": "足够的；相当多的；足够地；相当多地", "ex": "Tengo bastante tiempo para terminar el trabajo.", "lvl": "A2"},
{"t": "general", "es": "bidireccional", "pos": "adj.", "zh": "双向的", "ex": "Esta calle es bidireccional y hay mucho tráfico.", "lvl": "B2"},
{"t": "emo", "es": "calurosos", "pos": "adj.", "zh": "炎热的；热情的", "ex": "Los días calurosos son perfectos para ir a la playa.", "lvl": "A2"},
{"t": "general", "es": "ciertas", "pos": "adj.", "zh": "真实的；确信的；某个；某些(用在名词前)；有点；对；确实", "ex": "En ciertas ocasiones, es mejor callar.", "lvl": "A2"},
{"t": "general", "es": "competidores", "pos": "adj.", "zh": "-s. 竞争的；竞争者；对手", "ex": "Los competidores presentaron sus propuestas ayer.", "lvl": "B1"},
{"t": "general", "es": "competitiva", "pos": "adj.", "zh": "竞争的；有竞争力的", "ex": "La empresa ofrece una tarifa competitiva.", "lvl": "B2"},
{"t": "general", "es": "concreta", "pos": "adj.", "zh": "具体的；凝结的；凝结；凝聚", "ex": "Necesito una respuesta concreta antes del lunes.", "lvl": "B1"},
{"t": "general", "es": "concretas", "pos": "adj.", "zh": "具体的；凝结的；凝结；凝聚", "ex": "La profesora pidió ideas concretas para el proyecto.", "lvl": "B1"},
{"t": "general", "es": "concretos", "pos": "adj.", "zh": "具体的；凝结的；凝结；凝聚", "ex": "Quiero ejemplos concretos de tu experiencia.", "lvl": "B1"},
{"t": "general", "es": "contenido", "pos": "adj.", "zh": "内在的；感情不外露的；有克制能力的；装有的东西；内容", "ex": "El contenido de la película no es apto para niños.", "lvl": "B1"},
{"t": "general", "es": "cortesanas", "pos": "adj.", "zh": "宫廷的；殷勤有礼的；朝臣；宫廷侍从；高级妓女", "ex": "Las damas cortesanas vivían en el palacio.", "lvl": "B2"},
{"t": "general", "es": "decisiva", "pos": "adj.", "zh": "决定性的；坚决的；肯定的", "ex": "Su opinión fue decisiva en la votación.", "lvl": "B2"},
{"t": "general", "es": "detestable", "pos": "adj.", "zh": "可恶的；极坏的", "ex": "Comer con la boca abierta es un hábito detestable.", "lvl": "B2"},
{"t": "general", "es": "distintas", "pos": "adj.", "zh": "不相同的；不一样的；明显的", "ex": "En la fiesta había personas de distintas edades.", "lvl": "B1"},
{"t": "general", "es": "duraderos", "pos": "adj.", "zh": "经久的；耐用的；持久 的", "ex": "Estos zapatos son duraderos y cómodos.", "lvl": "B2"},
{"t": "general", "es": "elevados", "pos": "adj.", "zh": "高的；高尚的；崇高的", "ex": "Los precios elevados de la vivienda son un problema.", "lvl": "B1"},
{"t": "general", "es": "emisores", "pos": "adj.", "zh": "发射的；播送的；发行 的；发射机；广播电 台", "ex": "Los países emisores de CO2 tienen mucha responsabilidad.", "lvl": "B2"},
{"t": "general", "es": "errante", "pos": "adj.", "zh": "流浪的；漂泊不定的", "ex": "El perro errante busca un hogar.", "lvl": "B2"},
{"t": "salud", "es": "específicos", "pos": "adj.", "zh": "特有的；特定的；具体的；(症状)特殊的；有特效的；特效药", "ex": "El médico pidió análisis específicos para el diagnóstico.", "lvl": "B1"},
{"t": "general", "es": "estables", "pos": "adj.", "zh": "稳定的；稳固的；固定的；持久的；永久的", "ex": "Los precios estables ayudan a la economía.", "lvl": "B1"},
{"t": "general", "es": "estadounidenses", "pos": "adj.", "zh": "美利坚合众国的；美国的；美国人的；f.美国人", "ex": "Muchas empresas estadounidenses invierten en tecnología.", "lvl": "B1"},
{"t": "edu", "es": "estéticos", "pos": "adj.", "zh": "美学的；美感的；美的；艺术的；审美的；具有审美趣味的", "ex": "Los criterios estéticos cambian con el tiempo.", "lvl": "B2"},
{"t": "general", "es": "excesiva", "pos": "adj.", "zh": "过分的；过多的", "ex": "La velocidad excesiva es peligrosa en la carretera.", "lvl": "B1"},
{"t": "general", "es": "externos", "pos": "adj.", "zh": "外面的；外部的；表露的；不住宿的；走读生", "ex": "Los factores externos influyen en nuestras decisiones.", "lvl": "B1"},
{"t": "general", "es": "fijos", "pos": "adj.", "zh": "固定的；不变的；定居的；肯定地；固定地", "ex": "Tiene horarios fijos en su nuevo trabajo.", "lvl": "B1"},
{"t": "general", "es": "fundadas", "pos": "adj.", "zh": "创立的；有根据的", "ex": "Sus críticas estaban fundadas en datos reales.", "lvl": "B2"},
{"t": "general", "es": "fundamentales", "pos": "adj.", "zh": "基础的；基本的；根本的", "ex": "El respeto y la educación son valores fundamentales.", "lvl": "B1"},
{"t": "general", "es": "griegos", "pos": "adj.", "zh": "希腊的；f. 希腊人", "ex": "Los filósofos griegos pensaron sobre la vida.", "lvl": "B1"},
{"t": "general", "es": "hechos", "pos": "adj.", "zh": "已经做好的；现成的；成熟的；样子像...的；行为；行动；事情；事件；事实", "ex": "Los hechos demuestran que tenía razón.", "lvl": "B1"},
{"t": "general", "es": "hitos", "pos": "adj.", "zh": "紧挨着的；毗邻的；f. 界标；路标；靶子；目标", "ex": "Esos descubrimientos fueron hitos importantes de la ciencia.", "lvl": "B2"},
{"t": "diario", "es": "horarios", "pos": "adj.", "zh": "时刻的；钟表；时针；短针；时刻表；时间表", "ex": "Los horarios del tren cambian los fines de semana.", "lvl": "A2"},
{"t": "general", "es": "impresionante", "pos": "adj.", "zh": "给人以深刻印象的；感人的；动人的", "ex": "El castillo de noche era impresionante.", "lvl": "B1"},
{"t": "general", "es": "indispensables", "pos": "adj.", "zh": "不能推卸的；必需的", "ex": "El agua y la luz son indispensables para la vida.", "lvl": "B2"},
{"t": "general", "es": "inmediata", "pos": "adj.", "zh": "邻近的；立即的", "ex": "El accidente necesitaba atención médica inmediata.", "lvl": "B1"},
{"t": "general", "es": "immensas", "pos": "adj.", "zh": "无数的；无边无际的；极好的", "ex": "Desde la montaña se ven las llanuras immensas.", "lvl": "B2"},
{"t": "general", "es": "internas", "pos": "adj.", "zh": "内部的；寄宿的", "ex": "Las reglas internas de la empresa son estrictas.", "lvl": "B1"},
{"t": "general", "es": "jerárquicos", "pos": "adj.", "zh": "等级的；等级制的", "ex": "Los niveles jerárquicos de la empresa están bien definidos.", "lvl": "B2"},
{"t": "general", "es": "lucrativa", "pos": "adj.", "zh": "生利的；赚钱的；有利可图的", "ex": "La industria turística es muy lucrativa en esta región.", "lvl": "B2"},
{"t": "naturaleza", "es": "medios", "pos": "adj.", "zh": "一半的；中等的；中间的；半；有些；一半；中间；中指；环境", "ex": "Los medios de transporte públicos son muy baratos aquí.", "lvl": "B1"},
{"t": "naturaleza", "es": "mediterráneas", "pos": "adj.", "zh": "地中海的；内地的", "ex": "Las playas mediterráneas son ideales para veranear.", "lvl": "B2"},
{"t": "general", "es": "motivos", "pos": "adj.", "zh": "使动的；能动的；动机；目的；借口；(文艺作品的)主题；旋律", "ex": "No conozco los motivos de su decisión.", "lvl": "B1"},
{"t": "general", "es": "mundiales", "pos": "adj.", "zh": "世界的；全世界的", "ex": "Los problemas mundiales requieren soluciones globales.", "lvl": "B1"},
{"t": "general", "es": "nómadas", "pos": "adj.", "zh": "游牧的；流浪的", "ex": "Los pueblos nómadas se desplazan buscando pastos.", "lvl": "B2"},
{"t": "general", "es": "obligatorias", "pos": "adj.", "zh": "强制性的；必须履行的；应尽的", "ex": "Las clases de natación son obligatorias en ese colegio.", "lvl": "B1"},
{"t": "general", "es": "operativa", "pos": "adj.", "zh": "操作的；运转着的；实施的；起作用的；有效的", "ex": "La empresa busca una estrategia operativa más eficiente.", "lvl": "B2"},
{"t": "general", "es": "pasivos", "pos": "adj.", "zh": "被动的；消极的；养老的；抚恤的；被动(语)态的；负债；债务", "ex": "Los fumadores pasivos también sufren los efectos del tabaco.", "lvl": "B2"},
{"t": "general", "es": "patronales", "pos": "adj.", "zh": "支持的；赞助的；保护的；企业主的；企业工会", "ex": "Las asociaciones patronales negociaron con los sindicatos.", "lvl": "B2"},
{"t": "naturaleza", "es": "pesqueros", "pos": "adj.", "zh": "捕鱼的；渔业的；渔船；渔轮", "ex": "Los barcos pesqueros salen al amanecer.", "lvl": "B2"},
{"t": "general", "es": "pocas", "pos": "adj.", "zh": "少的；少量的；不充足的；少；不多；片刻；少许", "ex": "Hay pocas personas en la calle hoy.", "lvl": "A1"},
{"t": "general", "es": "principales", "pos": "adj.", "zh": "首要的；本质的；杰出的；为首的；最初的；负责人；本钱；本金", "ex": "La contaminación es uno de los problemas principales de la ciudad.", "lvl": "B1"},
{"t": "general", "es": "propia", "pos": "adj.", "zh": "自己的；固有的；特有的；本来的", "ex": "Cada país tiene su propia cultura y tradiciones.", "lvl": "A2"},
{"t": "general", "es": "próximas", "pos": "adj.", "zh": "临近的；接近的；下一个的；将临的", "ex": "Las próximas vacaciones las pasaremos en la playa.", "lvl": "A2"},
{"t": "general", "es": "próximos", "pos": "adj.", "zh": "临近的；接近的；下一个的；将临的", "ex": "Los próximos días serán muy calurosos.", "lvl": "A2"},
{"t": "general", "es": "puesto", "pos": "adj.", "zh": "放置好的；穿戴好的；地方；地点；位置；货摊；职位；岗位；名次；岗哨；哨所", "ex": "Ella consiguió un buen puesto en la empresa.", "lvl": "B1"},
{"t": "emo", "es": "querido", "pos": "adj.", "zh": "亲爱的；情人", "ex": "Mi querido amigo siempre me apoya.", "lvl": "A2"},
{"t": "general", "es": "receptora", "pos": "adj.", "zh": "接收的；接收员；接待员", "ex": "La antena receptora capta la señal con claridad.", "lvl": "B2"},
{"t": "general", "es": "remarcables", "pos": "adj.", "zh": "杰出的；卓越的", "ex": "Sus logros remarcables le dieron un premio nacional.", "lvl": "B2"},
{"t": "general", "es": "restante", "pos": "adj.", "zh": "剩余的；剩余", "ex": "El tiempo restante lo dedicamos a repasar.", "lvl": "B2"},
{"t": "naturaleza", "es": "sedentarias", "pos": "adj.", "zh": "(职业、生活)极少活动的；坐着的；(部族、动物) 定居的", "ex": "Las tribus sedentarias cultivaban sus propios alimentos.", "lvl": "B2"},
{"t": "general", "es": "sobrante", "pos": "adj.", "zh": "过剩的；多余的；剩余物", "ex": "El dinero sobrante lo guardamos para emergencias.", "lvl": "B2"},
{"t": "general", "es": "succesivas", "pos": "adj.", "zh": "连续的；接连的；相继的", "ex": "El club celebró tres fiestas succesivas en mayo.", "lvl": "B1"},
{"t": "emo", "es": "susceptibles", "pos": "adj.", "zh": "敏感的；多心的；能感受的", "ex": "Las plantas son susceptibles a los cambios de temperatura.", "lvl": "B2"},
{"t": "general", "es": "tanta", "pos": "adj.", "zh": "这么多的", "ex": "No he visto tanta gente en el concierto.", "lvl": "A1"},
{"t": "viajes", "es": "turística", "pos": "adj.", "zh": "旅游的；观光的", "ex": "La zona turística está llena de restaurantes.", "lvl": "A2"},
{"t": "general", "es": "únicos", "pos": "adj.", "zh": "唯一的；独特的", "ex": "Estos son los únicos zapatos que me quedan bien.", "lvl": "B1"},
{"t": "general", "es": "vencido", "pos": "adj.", "zh": "被战胜的；被击败的；到期的；逾期的；过期失效的；被击败的人；失败者", "ex": "El billete de autobús está vencido.", "lvl": "B1"},
{"t": "general", "es": "vertiginosa", "pos": "adj.", "zh": "致眩晕的；令人头晕目眩的；高速的", "ex": "La velocidad vertiginosa del coche me asustó.", "lvl": "B2"},
{"t": "general", "es": "aún", "pos": "adv.", "zh": "还；现在；更加", "ex": "Aún no he terminado mis deberes.", "lvl": "A2"},
{"t": "general", "es": "aun", "pos": "adv.", "zh": "甚至；尽管", "ex": "Aun con lluvia, iremos a la playa.", "lvl": "B1"},
{"t": "general", "es": "allende", "pos": "adv.", "zh": "-prep. 在...那边；此外；除了...外", "ex": "Allende los montes se encuentra el pueblo natal de mi padre.", "lvl": "B2"},
{"t": "general", "es": "absolutamente", "pos": "adv.", "zh": "绝对地；完全地；决不", "ex": "Estoy absolutamente seguro de mi respuesta.", "lvl": "B1"},
{"t": "general", "es": "adelante", "pos": "adv.", "zh": "向前；迎面；将来；前进!；请进!；请继续下去", "ex": "Sigue adelante con tu proyecto aunque sea difícil.", "lvl": "A2"},
{"t": "general", "es": "anteriormente", "pos": "adv.", "zh": "在...之前；在前；事先；一会儿之前", "ex": "Anteriormente vivía en Madrid, ahora en Barcelona.", "lvl": "B1"},
{"t": "general", "es": "como", "pos": "adv.", "zh": "好像；正如；作为；由于；因为", "ex": "Ella trabaja como enfermera en el hospital.", "lvl": "A1"},
{"t": "general", "es": "detenidamente", "pos": "adv.", "zh": "仔细地", "ex": "Lee el contrato detenidamente antes de firmarlo.", "lvl": "B2"},
{"t": "general", "es": "firmemente", "pos": "adv.", "zh": "牢固地；坚定地；坚决地", "ex": "Creo firmemente en el poder de la educación.", "lvl": "B2"},
{"t": "general", "es": "francamente", "pos": "adv.", "zh": "坦率地；真正地；确实地", "ex": "Francamente, no me gusta esa película.", "lvl": "B1"},
{"t": "general", "es": "per cápita", "pos": "adv.", "zh": "按人头计算地；每人平均地: rendimiento ~ 每人平均产量.", "ex": "El ingreso per cápita del país aumentó este año.", "lvl": "B2"},
{"t": "general", "es": "permanentemente", "pos": "adv.", "zh": "持久地；稳定地；不变地", "ex": "Ahora vive permanentemente en el extranjero.", "lvl": "B2"},
{"t": "general", "es": "seguramente", "pos": "adv.", "zh": "确实地；肯定地；极可能地", "ex": "Seguramente mañana va a llover y hará frío.", "lvl": "B1"},
{"t": "general", "es": "solamente", "pos": "adv.", "zh": "仅仅；只是", "ex": "Solamente quedan dos entradas para el concierto.", "lvl": "A2"},
{"t": "general", "es": "totalmente", "pos": "adv.", "zh": "完全；全部地", "ex": "Estoy totalmente de acuerdo con lo que dices.", "lvl": "B1"},
{"t": "general", "es": "siquiera", "pos": "conj.", "zh": "即使；或者；至少", "ex": "Ni siquiera me saludó en la calle.", "lvl": "B1"},
{"t": "general", "es": "barrero", "pos": "s.", "zh": "陶器工人；出陶土的地方", "ex": "El barrero hizo vasijas con barro del río.", "lvl": "B2"},
{"t": "general", "es": "deceno", "pos": "s.", "zh": "第十的", "ex": "Vive en el deceno piso del edificio.", "lvl": "B2"},
{"t": "general", "es": "rotar", "pos": "s.", "zh": "旋转；转动；滚动", "ex": "La Tierra tarda un día en rotar sobre su eje.", "lvl": "B1"},
{"t": "general", "es": "ideológico", "pos": "s.", "zh": "思想上的；意识形态；观念学的", "ex": "El discurso ideológico del líder convenció a muchos.", "lvl": "B2"},
{"t": "general", "es": "conceptual", "pos": "s.", "zh": "概念上的", "ex": "El mapa conceptual ayuda a estudiar mejor.", "lvl": "B2"},
{"t": "general", "es": "relevancia", "pos": "s.", "zh": "重要；意义；突出；显著", "ex": "Este tema tiene mucha relevancia en la actualidad.", "lvl": "B2"},
{"t": "general", "es": "nuboso", "pos": "s.", "zh": "阴天", "ex": "El cielo está nuboso hoy por la mañana.", "lvl": "B1"},
{"t": "general", "es": "demográfico", "pos": "s.", "zh": "人口统计的；人口统计学的", "ex": "El crecimiento demográfico del país es muy alto.", "lvl": "B2"},
{"t": "naturaleza", "es": "medioambiental", "pos": "s.", "zh": "环境保护的", "ex": "El impacto medioambiental de la fábrica preocupa a todos.", "lvl": "B2"},
{"t": "general", "es": "falcón", "pos": "s.", "zh": "隼", "ex": "El falcón es un ave rapaz muy rápida.", "lvl": "B2"},
{"t": "general", "es": "controlable", "pos": "s.", "zh": "可控制", "ex": "La situación todavía es controlable si actuamos pronto.", "lvl": "B2"},
{"t": "general", "es": "homónimo", "pos": "s.", "zh": "同名的", "ex": "Mi amigo es homónimo del famoso cantante.", "lvl": "B2"},
{"t": "general", "es": "divertimento", "pos": "s.", "zh": "余兴", "ex": "El divertimento de la fiesta fue un espectáculo de magia.", "lvl": "B2"},
{"t": "general", "es": "subjetivismo", "pos": "s.", "zh": "主观主义", "ex": "El subjetivismo impide ver los hechos con claridad.", "lvl": "B2"},
{"t": "general", "es": "charter", "pos": "s.", "zh": "宪章", "ex": "El charter de las Naciones Unidas defiende los derechos humanos.", "lvl": "B2"},
{"t": "salud", "es": "motricidad", "pos": "s.", "zh": "[生理]运动机能", "ex": "El ejercicio mejora la motricidad de los niños.", "lvl": "B2"},
{"t": "general", "es": "souvenir", "pos": "s.", "zh": "纪念品", "ex": "Compré un souvenir de mi viaje a México.", "lvl": "B1"},
{"t": "general", "es": "reenvio", "pos": "s.", "zh": "转发", "ex": "Haz el reenvio del correo a todos los empleados.", "lvl": "B1"},
{"t": "naturaleza", "es": "termalismo", "pos": "s.", "zh": "水疗", "ex": "El termalismo atrae a muchos turistas a esta ciudad.", "lvl": "B2"},
{"t": "general", "es": "a causa de", "pos": "s.", "zh": "因为；由于", "ex": "El partido se canceló a causa de la lluvia.", "lvl": "A2"},
{"t": "general", "es": "a menudo", "pos": "s.", "zh": "经常", "ex": "Mi abuela nos visita a menudo.", "lvl": "A2"},
{"t": "general", "es": "a raíz de", "pos": "s.", "zh": "继……之后；接近；贴近", "ex": "A raíz de aquel accidente, mejoraron las carreteras.", "lvl": "B2"},
{"t": "general", "es": "al principio", "pos": "s.", "zh": "起初；开始", "ex": "Al principio no entendía la clase, pero ahora sí.", "lvl": "A2"},
{"t": "general", "es": "amortiguación", "pos": "s.", "zh": "减震", "ex": "La amortiguación de la bicicleta hace cómodo el camino.", "lvl": "B2"},
{"t": "general", "es": "brutalmente", "pos": "s.", "zh": "粗暴地", "ex": "El ladrón golpeó brutalmente a la víctima.", "lvl": "B2"},
{"t": "general", "es": "cazamoscas", "pos": "s.", "zh": "蛛蛛", "ex": "El cazamoscas atrapa los insectos de la cocina.", "lvl": "B2"},
{"t": "general", "es": "condicionan", "pos": "s.", "zh": "条件", "ex": "Los horarios condicionan mi vida diaria.", "lvl": "B1"},
{"t": "general", "es": "corrientes", "pos": "s.", "zh": "科连特斯", "ex": "Mis primos viven en Corrientes, Argentina.", "lvl": "B1"},
{"t": "general", "es": "emisora", "pos": "s.", "zh": "广播电台", "ex": "La emisora local transmite las noticias a las ocho.", "lvl": "B1"},
{"t": "general", "es": "emisoras", "pos": "s.", "zh": "广播电台", "ex": "Varias emisoras emitieron el partido en directo.", "lvl": "B1"},
{"t": "general", "es": "en vez de", "pos": "s.", "zh": "而不是...", "ex": "Tomé el autobús en vez de caminar.", "lvl": "A2"},
{"t": "general", "es": "encarecidamente", "pos": "s.", "zh": "高度", "ex": "Le ruego encarecidamente que revise su solicitud.", "lvl": "B2"},
{"t": "general", "es": "equitativamente", "pos": "s.", "zh": "公平", "ex": "Repartiremos los beneficios equitativamente entre todos.", "lvl": "B2"},
{"t": "general", "es": "extendióndose", "pos": "s.", "zh": "蔓延；扩散；伸展", "ex": "El incendio se fue extendióndose durante toda la noche.", "lvl": "B2"},
{"t": "general", "es": "fraccionamiento", "pos": "s.", "zh": "分割；分裂", "ex": "El fraccionamiento de la herencia causó problemas familiares.", "lvl": "B2"},
{"t": "general", "es": "frecuentemente", "pos": "s.", "zh": "经常地；频繁地", "ex": "Mis padres viajan frecuentemente por trabajo.", "lvl": "B1"},
{"t": "general", "es": "fundamentalmente", "pos": "s.", "zh": "从根本上", "ex": "Su decisión se basa fundamentalmente en razones económicas.", "lvl": "B2"},
{"t": "general", "es": "hacer falta", "pos": "s.", "zh": "必须；需要", "ex": "Si quieres aprender, te va a hacer falta estudiar más.", "lvl": "A2"},
{"t": "general", "es": "homogeneización", "pos": "s.", "zh": "同质化", "ex": "La homogeneización de la cultura preocupa a muchos expertos.", "lvl": "B2"},
{"t": "general", "es": "inmobiliaria", "pos": "s.", "zh": "不动产的", "ex": "La agencia inmobiliaria me mostró varios pisos.", "lvl": "B2"},
{"t": "general", "es": "integrados", "pos": "s.", "zh": "种族融合的", "ex": "Los niños integrados aprenden junto a los demás.", "lvl": "B1"},
{"t": "naturaleza", "es": "medioambientales", "pos": "s.", "zh": "环境保护的", "ex": "Los problemas medioambientales afectan a todo el planeta.", "lvl": "B2"},
{"t": "general", "es": "orientadas", "pos": "s.", "zh": "导向", "ex": "Las actividades orientadas al deporte son muy populares.", "lvl": "B1"},
{"t": "general", "es": "peinarse", "pos": "s.", "zh": "梳理 (毛发)", "ex": "Ella tarda diez minutos en peinarse cada mañana.", "lvl": "A2"},
{"t": "general", "es": "positiva", "pos": "s.", "zh": "正", "ex": "Recibimos una respuesta positiva de la empresa.", "lvl": "B1"},
{"t": "general", "es": "prácticamente", "pos": "s.", "zh": "实质上", "ex": "Los precios subieron prácticamente en todo el país.", "lvl": "B1"},
{"t": "general", "es": "reevaluar", "pos": "s.", "zh": "重新评价", "ex": "El gobierno debe reevaluar su política educativa.", "lvl": "B2"},
{"t": "general", "es": "saturados", "pos": "s.", "zh": "饱和的", "ex": "Los mercados están saturados de productos similares.", "lvl": "B2"},
{"t": "general", "es": "sobre todo", "pos": "s.", "zh": "特别；尤其", "ex": "Me gusta el deporte, sobre todo el fútbol.", "lvl": "A2"},
{"t": "general", "es": "teniendo en cuenta", "pos": "s.", "zh": "鉴于", "ex": "Teniendo en cuenta el tiempo, saldremos temprano.", "lvl": "B1"}
];
// 合并进全局 VDATA(与 vdata_dele.js 相同的去重合并模式)
(function(){
  if(typeof VDATA==='undefined'||typeof VDATA_BATCH1==='undefined') return;
  var _existingB1=new Set(VDATA.map(function(v){return v.es;}));
  VDATA_BATCH1.forEach(function(v){ if(!_existingB1.has(v.es)){VDATA.push(v);} });
})();
